var MAX_CACHE_SIZE=20;var HOME_CLASS_IDENTIFIER="Home";var NAV_CLASS_IDENTIFIER="Nav";var FIRST_CONTAINER_ID="dmFirstContainer";var SECOND_CONTAINER_ID="dmSecondContainer";var GALLERY_CONTAINER_ID="dmGalleryContainer";
var GALLERY_CONTAINER_ID_IMG="dmGalleryImage";var GALLERY_BLACK_CONTAINER_ID="dmBlackContainer";var docWriteCalled=false;var isNewNav=false;var afterExpCol=null;function Enum(){}Enum.AnimationType={None:0,SlideLeft:1,SlideRight:2,Rotate:3,Fade:4};
Enum.LinkType={Home:0,Nav:1,Other:2};Enum.WebPlatformType={General:0,Webs:1,Attsmb:2,WebsPlanet:3,Blogs:4};Enum.AgentType={Iphone:0,Android:1,BlackBerry:2,Nokia:3,WindowsMobile:4,Other:5};Enum.ThemeType={Matrix:0,Other:1};
function parametersClass(){this.AjaxContainer="div.dmBody";this.WrappingContainer="div.dmOuter";this.BackgroundElement="div.dmInner";this.HomeUrl=null;this.CurrentPageUrl=null;this.IsCurrentHomePage=null;
this.CurrentLinkType=null;this.SiteAlias=null;this.InitialPageAlias="home";this.DefaultPageAlias="home";this.AnimationTypeForward=Enum.AnimationType.SlideLeft;this.AnimationTypeBackward=Enum.AnimationType.SlideRight;
this.AnimationTypeInner=Enum.AnimationType.Fade;this.Charset="UTF-8";this.CacheSize=10;this.AllowAjax=true;this.LinksToAjax="a[href^='/site/'], a[href^='#/site/'], a[href^='#'] , .u_dmStyle_backToHome";
this.BeforeAjaxCommand=null;this.AfterAjaxCommand=null;this.StartupCommand=null;this.WebsiteGenerator=Enum.WebPlatformType.General;this.SelectorsToHideOnTransitions=null;this.HomeLinksClasses="dm-logo-anchor";
this.HomeLinkText="Back to home";this.HomeLinkSelector="a.dmHome";this.UseGalleryModule=false;this.CurrentThemeName="";this.DisableLinks=false;this.LinksToAjaxExceptions=[];this.NavParameters=function(){this.NavbarSize=5;
this.NavbarSelector=".dmNav";this.SubNavbarSelector="";this.NavbarLiveHomePage=null;this.BlockContainerSelector=".dmBody";this.ShowBackToHomeOnInnerPages=true;this.MoreButtonText="More Options";this.LessButtonText="Less Options";
this.ReplaceNavigationOnInnerPages=true};this.SidebarParameters=function(){this.SidebarSelector=".dm_sideBar";this.SidebarArrowSelector="#fw-sidebar-arrow";this.SidebarInitialClass="fw-sidebarbegin";this.SidebarClosingClass="fw-sidebarend"
};this.NavigationAreaParams=new this.NavParameters();this.SidebarParams=new this.SidebarParameters()}var Parameters=new parametersClass();(function($){function Page(pageURL){this.pageUrl=pageURL;this.pageContent=null;
this.ajaxCallComplete=false;this.linkType=Enum.LinkType.Other;this.pageUrlIdentifier=hex_sha1(this.pageUrl);this.pageID=this.pageUrlIdentifier+"";this.pageScrollTo=null;this.pageReady=false;this.pageAnimation=null
}Page.prototype.equals=function(page){return this.pageUrl==page.pageUrl};Page.prototype.render=function(){setLoadingOnScreen(true);loadPageData(this,false)};Page.prototype.show=function(pushToStack){if(_currentPage==null){return
}if(pushToStack==null){pushToStack=true}if(_currentPage.pageUrl==this.pageUrl){}_frameworkReady=false;_currentPage=this;if(_tempDocumentWrite!=null){document.write=_tempDocumentWrite}if(this.pageContent==null){loadPageData(this);
displayPage(this,true,pushToStack)}else{displayPage(this,false,pushToStack)}};Page.prototype.scrollTo=function(){if(this.pageScrollTo!=null){if($("a[name="+this.pageScrollTo+"]").length>0){$("body, html").scrollTop($("a[name="+this.pageScrollTo+"]").offset().top)
}else{if($("a[id="+this.pageScrollTo+"]").length>0){$("body, html").scrollTop($("a[id="+this.pageScrollTo+"]").offset().top)}else{if($("div[id="+this.pageScrollTo+"]").length>0){$("body, html").scrollTop($("div[id="+this.pageScrollTo+"]").offset().top)
}}}}};var _ajaxContainer=null;var _wrappingContainer=null;var _currentPage=null;var _nextPage=null;var _ajaxContainerTemp=null;var _jQueryVar=$;var _frameworkReady=false;var _cacheDB=new Object();var _cacheStack=[];
var _useLocalStorage=false;var _linksToAjaxExceptionsDefaults=["/site/wrap","/site/classic","fw_comments_page","/profile/messages/compose","/profile/messages/compose","/site/sms","/site/emailShare","apps%2Fauth%2Fsignup"];
var _onclickPermittedValues=[null,"","return true;","return true"];var _animationsArray=new Array();_animationsArray[Enum.AnimationType.None]=new noAnimation();_animationsArray[Enum.AnimationType.SlideLeft]=new SlideLeftAnimation();
_animationsArray[Enum.AnimationType.SlideRight]=new SlideRightAnimation();_animationsArray[Enum.AnimationType.Rotate]=new RotateAnimation();_animationsArray[Enum.AnimationType.Fade]=new FadeAnimation();
var _LandingPageIdentifier="0000";var _userAgent=Enum.AgentType.Other;var _ThemeType=Enum.ThemeType.Other;var _=new Object();var _tempDocumentWrite=null;$.DM=_;_.setParameters=function(){if(Parameters.AllowAjax){setParametersInsideMembersForAjaxWebsites()
}else{setParametersInsideMembersForNonAjaxWebsites()}};_.enableAnimations=function(){Parameters.AnimationTypeForward=Enum.AnimationType.SlideLeft;Parameters.AnimationTypeBackward=Enum.AnimationType.SlideRight;
Parameters.AnimationTypeInner=Enum.AnimationType.Rotate};_.disableAnimations=function(){Parameters.AnimationTypeForward=Enum.AnimationType.None;Parameters.AnimationTypeBackward=Enum.AnimationType.None;
Parameters.AnimationTypeInner=Enum.AnimationType.None};_.updateWidth=function(){$("body").css("min-width",$(window).width())};_.updateIOSHeight=function(height,width){if(navigator.userAgent.match(/iPad/i)){height=height||$(window).height();
width=width||$(window).width();jQuery("#iOSWrapper").css("height",height);$("body").css("min-width",width);if(typeof myScroll!="undefined"){setTimeout("myScroll.refresh();",100);setTimeout("myScroll.refresh();",1000);
setTimeout("myScroll.refresh();",5000)}}};_.isCurrentHomePage=function(){return _currentPage.linkType==Enum.LinkType.Home};_.getHomeLink=function(){var urlParams=getUrlPremiumParams();if(urlParams.length>0){urlParams="&"+urlParams
}return Parameters.HomeUrl+"?url="+Parameters.NavigationAreaParams.NavbarLiveHomePage+urlParams};_.jumpTo=function(selector,offset){try{offset=offset||0;$("body, html").scrollTop($(selector).offset().top+offset)
}catch(e){}};_.executeAjaxCommand=function(url,onSuccess,onFail){retrieveJqueryVar();$.ajax({url:url,contentType:"application/json",dataType:"json",success:function(data){onSuccess(data)},error:function(request,status,error){onFail(request,status,error);
log("DMAjax says: an external ajax command has returned with failure: "+request.responseText)}})};_.setLoadingOnScreen=function(visible,pos,changeSize,keepColor){setLoadingOnScreen(visible,pos,changeSize,keepColor)
};_.getPageScrollY=function(){return getPageScrollY()};_.getPageHeight=function(){return getPageHeight()};_.getPageWidth=function(){return getPageWidth()};_.blackScreen=function(show){var blackBox=$("#"+GALLERY_BLACK_CONTAINER_ID);
if(blackBox.length>0){if(show){blackBox.changeDisplay("block");blackBox.height(getPageScrollY()+getPageHeight()+100)}else{blackBox.changeDisplay("none")}}};_.initAjaxLinks=function(specificLinks){initAjaxLinks(specificLinks)
};_.setCachedPageContent=function(pageURL,newContent){if(pageURL.indexOf("url=")!=-1){pageURL=unescape(getParamValue(pageURL,"url"))}var page=findInCacheByUrl(pageURL);if(page!=null){page.pageContent=newContent
}};_.hasMoreLessButtons=function(){return(jQuery(".dmMore").length>0||jQuery(".dmLess").length>0)};_.assignLoaderColor=function(elementSelector){assignLoaderColor(elementSelector)};_.backToMenuButtonWasClicked=function(showSub){$("#expandableSubDiv").toggle(showSub);
$("#expandableMainDiv").toggle(!showSub);$("#expandableNavigationContainer").parent().attr("movedToMain",showSub?"":"true");_afterExpandCollapse()};_.openCloseRSS=function(el){var $el=$(el).parent();var oldHeight=$el.attr("_oldHeight");
if(oldHeight&&oldHeight.length>0){$el.attr("_oldHeight","");$el.attr("style","");$el.find(".dmListItemDescriptionDiv:first").css("max-height",oldHeight);$el.parent().removeClass("parentOfOpenDescription");
_afterExpandCollapse()}else{$el.attr("_oldHeight",$el.find(".dmListItemDescriptionDiv:first").css("max-height"));$el.attr("style","");$el.find(".dmListItemDescriptionDiv:first").css("max-height","none");
$el.parent().addClass("parentOfOpenDescription");_afterExpandCollapse()}};_.expandableMenuWasClicked=function(openNav){var expandableContainer=$("#expandableNavigationContainer");var parentDiv=expandableContainer.parent();
var open=(openNav===undefined)?!expandableContainer.hasClass("expandableMenuOpen"):openNav;expandableContainer.unbind("webkitTransitionEnd");expandableContainer.unbind("transitionend");expandableContainer.unbind("oTransitionEnd");
var blackBox=$("#"+GALLERY_BLACK_CONTAINER_ID);if(blackBox.length==0){blackBox=$('<div ID="'+GALLERY_BLACK_CONTAINER_ID+'"></div>');blackBox.css("position","absolute");blackBox.changeDisplay("none");blackBox.css("overflow","hidden");
blackBox.css("left","0px").css("top","0px");blackBox.css("background-color","black");blackBox.css("opacity","0.5");blackBox.css("z-index","99999");blackBox.changeDisplay("none");blackBox.css("width",$(window).width()+"px").css("height","100%");
blackBox.attr("class","dmNoMargin");$("#dmFirstContainer").append(blackBox).css("position","relative");blackBox.unbind("click").click(function(){jQuery.DM.expandableMenuWasClicked()});$(window).unbind("resize.expand").bind("resize.expand",function(){expandableContainer.css("width",$(window).width()+"px");
blackBox.css("width",$(window).width()+"px")})}if(open){expandableContainer.show();blackBox.changeDisplay("block");blackBox.height("height","100%");expandableContainer.css("width",$(window).width()+"px");
var curBg=$(".dmInner").css("background-color");parentDiv.css("z-index","999999998");parentDiv.css("position","relative");expandableContainer.addClass("expandableMenuOpen");expandableContainer.removeClass("expandableMenuClose");
parentDiv.addClass("expandableParentMenuOpen");parentDiv.removeClass("expandableParentMenuClose")}else{expandableContainer.addClass("expandableMenuClose");expandableContainer.removeClass("expandableMenuOpen");
parentDiv.addClass("expandableParentMenuClose");parentDiv.removeClass("expandableParentMenuOpen");if(!!parentDiv.attr("movedToMain")){$("#expandableSubDiv").show();$("#expandableMainDiv").hide();parentDiv.attr("movedToMain","")
}blackBox.changeDisplay("none");setTimeout(function(){expandableContainer.css("width","");expandableContainer.hide()},0)}_afterExpandCollapse()};function isLocalStorageSupported(){if(window.localStorage){try{localStorage.setItem("testKey",1);
localStorage.removeItem("testKey");return true}catch(e){return false}}return false}isIE7=function(){var match=$.uaMatch(navigator.userAgent);return match.browser=="msie"&&(match.version<8||document.documentMode<8)
};isIE8=function(){var match=$.uaMatch(navigator.userAgent);return((match.browser=="msie")&&(match.version<9||document.documentMode<9)&&(!isIE7()))};function initCache(){if(isLocalStorageSupported()&&Parameters.AllowAjax&&(_userAgent!=Enum.AgentType.Android)&&(!(isIE8()||isIE7()))){_cacheStack=[];
_useLocalStorage=true;_cacheDB=localStorage;_cacheDB.clear()}}initFramework=function(){if(!_frameworkReady){initCache();Parameters.LinksToAjaxExceptions=_linksToAjaxExceptionsDefaults.concat(Parameters.LinksToAjaxExceptions);
if(Parameters.AllowAjax){setParametersInsideMembersForAjaxWebsites()}else{setParametersInsideMembersForNonAjaxWebsites()}if(!isBrowserSupportTransitions()||!Parameters.AllowAjax){_.disableAnimations()}if(Parameters.UseGalleryModule){initGalleryModule()
}_.afterAjaxGeneralInits();_.preloadImages();_frameworkReady=true}};function loadExternalScriptAsync(url,onLoad){if($('script[src="'+url+'"]').length==0){var s=document.createElement("script");s.type="text/javascript";
s.async=true;s.src=url;if(onLoad){s.onload=onLoad}var x=document.getElementsByTagName("script")[0];x.parentNode.insertBefore(s,x)}else{if(onLoad){onLoad()}}}function getUrlPremiumParams(){var url=window.location.toString();
var returnStr="";var tryModeParam=getParamValue(url,"dm_try_mode");var premiumParam=getParamValue(url,"dm_package");var premiumwebs=getParamValue(url,"fw_sig_tier");if(tryModeParam!=null){returnStr+="dm_try_mode="+tryModeParam
}if(premiumParam!=null){returnStr+="dm_package="+premiumParam}else{if(premiumwebs!=null){returnStr+="fw_sig_tier="+premiumwebs}}return returnStr}function getParamValue(url,param){if(url==null){return null
}var splitter=url.split("?");var params="";if(splitter.length>1){params=splitter[1]}else{return null}params=params.split("#")[0];var paramSplit=params.split("&");for(var paramValIndex=0;paramValIndex<paramSplit.length;
paramValIndex++){var paramVal=paramSplit[paramValIndex];paramValSplit=paramVal.split("=");if(paramValSplit.length==2){if(paramValSplit[0]==param){return paramValSplit[1]}}}return null}function initGalleryModule(){var module=$("#"+GALLERY_CONTAINER_ID);
if(module.length==0){module=$('<div ID="'+GALLERY_CONTAINER_ID+'"></div>');module.css("position","absolute");module.changeDisplay("none");module.css("z-index","100000");module.css("left","0px");module.css("top","0px");
$("body").append(module)}var blackBox=$("#"+GALLERY_BLACK_CONTAINER_ID);if(blackBox.length==0){blackBox=$('<div ID="'+GALLERY_BLACK_CONTAINER_ID+'" ontouchmove="touchMove(event);"></div>');blackBox.css("position","absolute");
blackBox.changeDisplay("none");blackBox.css("overflow","hidden");blackBox.css("left","0px");blackBox.css("top","0px");blackBox.css("background-color","#000000");blackBox.css("opacity","0.8");blackBox.css("z-index","99999");
blackBox.changeDisplay("none");blackBox.width($(document).width());blackBox.height(getPageScrollY()+getPageHeight()+100);$("body").append(blackBox)}if(_userAgent!=Enum.AgentType.Other){if(_userAgent==Enum.AgentType.Iphone){module.unbind("orientationchange").bind("orientationchange",function(event){fitGalleryElementsToScreen()
})}else{window.addEventListener("orientationchange",function(){fitGalleryElementsToScreen()},false)}}}fitGalleryElementsToScreen=function(){var blackBox=$("#"+GALLERY_BLACK_CONTAINER_ID);var moduleImage=$("#"+GALLERY_CONTAINER_ID_IMG);
var module=$("#"+GALLERY_CONTAINER_ID);if(module.length>0&&blackBox.css("display")=="block"){blackBox.width($(document).width());blackBox.height(getPageScrollY()+getPageHeight()+100);var scaleFactor=null;
if(window.orientation!=0){scaleFactor=0.75}else{scaleFactor=0.85}var realImageWidth=moduleImage.data("originalWidth");var realImageHeight=moduleImage.data("originalHeight");var s=Math.min(getViewportScale(),Math.min(getPageHeight()/realImageHeight,getPageWidth()/realImageWidth));
s=s*scaleFactor;moduleImage.width(Math.round(realImageWidth*s));moduleImage.height(Math.round(realImageHeight*s));module.css({top:getPageScrollY()*1+((getPageHeight()-moduleImage.height()*1)/2)-8+"px",left:Math.round((getPageWidth()-moduleImage.width())/2)+"px"}).width(Math.round(moduleImage.width()))
}};function hideAdressBar(){setTimeout(function(){window.scrollTo(0,1)},1);$("body").bind("touchstart",function(){window.scrollTo(0,1)})}touchMove=function(event){event.preventDefault()};function setParametersInsideMembersForAjaxWebsites(){if(Parameters.AjaxContainer!=null){_ajaxContainer=Parameters.AjaxContainer;
_ajaxContainerTemp="#"+SECOND_CONTAINER_ID}if(Parameters.WrappingContainer!=null){_wrappingContainer=Parameters.WrappingContainer}else{Parameters.AnimationTypeForward=Enum.AnimationType.None;Parameters.AnimationTypeBackward=Enum.AnimationType.None;
Parameters.AnimationTypeInner=Enum.AnimationType.None}if(Parameters.CacheSize!=null){if(Parameters.CacheSize>MAX_CACHE_SIZE){_Parameters.CacheSize=MAX_CACHE_SIZE}}if(Parameters.NavigationAreaParams.NavbarSize==-1||$.uaMatch(navigator.userAgent).browser=="opera"){Parameters.NavigationAreaParams.NavbarSize=Number.MAX_VALUE
}if(_ajaxContainer==null||Parameters.HomeUrl==null||_currentPage==null||Parameters.SiteAlias==null){}if(Parameters.CurrentPageUrl!=null){var hash=window.location.hash;if(hash!=null&&hash!=""){hash=hash.replace("#","")
}var p=findInCache(hash);if(p!=null){_currentPage=createPageFromCachedJson(p);window.location.hash=_currentPage.pageID;if(document.readyState!=="complete"&&_currentPage.pageContent.isHomePage){}else{_currentPage.show()
}}else{_currentPage=new Page(Parameters.CurrentPageUrl);window.location.hash=_currentPage.pageID;if(Parameters.CurrentLinkType!=null){_currentPage.linkType=Parameters.CurrentLinkType}if((Parameters.IsCurrentHomePage!=null)&&(_currentPage!=null)){if(Parameters.IsCurrentHomePage){_currentPage.linkType=Enum.LinkType.Home;
_currentPage.pageUrl=_.getHomeLink()}var content="<div id='"+$(_ajaxContainer).attr("id")+"' class='"+$(_ajaxContainer).attr("class")+"'>"+$(_ajaxContainer).html()+"</div>";if(!docWriteCalled){_currentPage.pageContent={content:content,isHomePage:Parameters.IsCurrentHomePage,css:$("#pagestyle").html(),alias:Parameters.InitialPageAlias}
}}}_LandingPageIdentifier=_currentPage.pageUrlIdentifier;_cacheStack.push(_currentPage.pageID);addToCache(_currentPage);_tempDocumentWrite=document.write;document.write=function(s){}}}function setParametersInsideMembersForNonAjaxWebsites(){if(Parameters.AjaxContainer!=null){_ajaxContainer=Parameters.AjaxContainer;
$(_ajaxContainer).attr("ID",FIRST_CONTAINER_ID);_ajaxContainer="#"+FIRST_CONTAINER_ID}if(Parameters.WrappingContainer!=null){_wrappingContainer=Parameters.WrappingContainer}else{Parameters.AnimationTypeForward=Enum.AnimationType.None;
Parameters.AnimationTypeBackward=Enum.AnimationType.None;Parameters.AnimationTypeInner=Enum.AnimationType.None}if(Parameters.NavigationAreaParams.NavbarSize==-1||$.uaMatch(navigator.userAgent).browser=="opera"){Parameters.NavigationAreaParams.NavbarSize=Number.MAX_VALUE
}if(_ajaxContainer==null||Parameters.HomeUrl==null||_currentPage==null||Parameters.SiteAlias==null){}if(Parameters.CurrentPageUrl!=null){_currentPage=new Page(Parameters.CurrentPageUrl);_LandingPageIdentifier=_currentPage.pageUrlIdentifier
}if(Parameters.CurrentLinkType!=null){_currentPage.linkType=Parameters.CurrentLinkType}if((Parameters.IsCurrentHomePage!=null)&&(_currentPage!=null)){if(Parameters.IsCurrentHomePage){_currentPage.linkType=Enum.LinkType.Home
}if(Parameters.NavigationAreaParams.NavbarLiveHomePage!=null){_currentPage.pageUrl=_.getHomeLink()}else{_currentPage.pageUrl=_.getHomeLink()}}}function retrieveJqueryVar(){$=_jQueryVar}function isClassicMode(){return document.cookie!=null&&document.cookie.indexOf("dm_show_classic")!=-1
}function isLinkException(href){for(var i=0;i<Parameters.LinksToAjaxExceptions.length;i++){if(href.indexOf(Parameters.LinksToAjaxExceptions[i])!=-1||unescape(href).indexOf(Parameters.LinksToAjaxExceptions)!=-1){return true
}}return false}function initAjaxLinks(specificLinks){if(Parameters.DisableLinks==false){retrieveJqueryVar();_.updateWidth();if(Parameters.AllowAjax){var savedLinksSelector=null;if(specificLinks!=null){savedLinksSelector=Parameters.LinksToAjax;
Parameters.LinksToAjax=specificLinks}$(Parameters.LinksToAjax).each(function(index){if($(this).attr("href")!=null&&$(this).attr("href").startsWith("#")){$(this).attr("dmGoto",$(this).attr("href").replace("#",""));
$(this).removeAttr("href");$(this).css("cursor","pointer");$(this).css("cursor","hand");$(this).click(function(event){_currentPage.pageScrollTo=$(this).attr("dmGoto");_currentPage.scrollTo();if(event!=null){event.stopPropagation()
}})}else{if(isPermittedOnClickValue($(this).attr("onClick"))){if(!isLinkException($(this).attr("href"))){$(this).unbind("click").click(function(event){if(Parameters.AllowAjax){if(event!=null){if(isStopPropagationClickEvent($(this))){event.stopPropagation()
}event.preventDefault()}var href=$(this).attr("href");if(isClassicMode()){document.location=$("#classic_link").attr("href")}if(isLinkException(href)){return true}var anchorIndex=href.indexOf("#");var scrollTo=null;
if(anchorIndex!=-1){scrollTo=href.substr(anchorIndex+1)}_nextPage=findInCacheByUrl(unescape(getParamValue(href,"url")));if(_nextPage==null){_nextPage=new Page(href)}else{if(_useLocalStorage){_nextPage=createPageFromCachedJson(_nextPage)
}}if(scrollTo!=null){_nextPage.pageScrollTo=scrollTo}_nextPage.linkType=getLinkType($(this));_nextPage.pageAnimation="forward";var forcedAnimationValue=getForcedPageAnimationType($(this));if(forcedAnimationValue!=null){_nextPage.pageAnimation=forcedAnimationValue
}_nextPage.show()}})}}}});if(savedLinksSelector!=null){Parameters.LinksToAjax=savedLinksSelector;savedLinksSelector=null}}}}function createPageFromCachedJson(cachedJson){var p=new Page(cachedJson.pageUrl);
p.pageUrl=cachedJson.pageUrl;p.pageContent=cachedJson.pageContent;p.ajaxCallComplete=cachedJson.ajaxCallComplete;p.linkType=cachedJson.linkType;p.pageUrlIdentifier=cachedJson.pageUrlIdentifier;p.pageID=cachedJson.pageID;
p.pageScrollTo=cachedJson.pageScrollTo;p.pageReady=cachedJson.pageReady;p.pageAnimation=cachedJson.pageAnimation;return p}function isPermittedOnClickValue(value){for(var i=0;i<_onclickPermittedValues.length;
i++){if(value==_onclickPermittedValues[i]){return true}}return false}function isStopPropagationClickEvent(anchor){if(anchor.attr("href")!=null&&anchor.attr("href").startsWith("/site/")){return false}else{return true
}}function getLinkType(elm){var hrefClassIdentifier=elm.attr("class");var hrefParentClassIdentifier=elm.parent().attr("class");var hrefGrandpaClassIdentifier=elm.parent().parent().attr("class");var innerHrefText=elm.text()+"";
if(hrefClassIdentifier==null){hrefClassIdentifier=""}else{if(typeof(hrefClassIdentifier)=="undefined"){hrefClassIdentifier=""}}if(hrefParentClassIdentifier==null){hrefParentClassIdentifier=""}else{if(typeof(hrefParentClassIdentifier)=="undefined"){hrefParentClassIdentifier=""
}}if(hrefGrandpaClassIdentifier==null){hrefGrandpaClassIdentifier=""}else{if(typeof(hrefGrandpaClassIdentifier)=="undefined"){hrefGrandpaClassIdentifier=""}}if((hrefClassIdentifier.toLowerCase().indexOf(HOME_CLASS_IDENTIFIER.toLowerCase())!=-1)||(Parameters.HomeLinksClasses!=null&&hrefClassIdentifier.toLowerCase().indexOf(Parameters.HomeLinksClasses.toLowerCase())!=-1)){return Enum.LinkType.Home
}else{if(hrefClassIdentifier.toLowerCase().indexOf(NAV_CLASS_IDENTIFIER.toLowerCase())!=-1||hrefParentClassIdentifier.toLowerCase().indexOf(NAV_CLASS_IDENTIFIER.toLowerCase())!=-1||hrefGrandpaClassIdentifier.toLowerCase().indexOf(NAV_CLASS_IDENTIFIER.toLowerCase())!=-1){return Enum.LinkType.Nav
}else{return Enum.LinkType.Other}}}function getForcedPageAnimationType(elm){var type=elm.attr("animationType");if(!type||type==""){type=elm.attr("animationtype")}if(type=="backward"){return"backward"}else{if(type=="forward"){return"forward"
}else{if(type=="inner"){return"inner"}else{return null}}}}function loadPageData(page){retrieveJqueryVar();page.ajaxCallCompleted=false;if(Parameters.BeforeAjaxCommand!=null){try{Parameters.BeforeAjaxCommand()
}catch(e){log("DMAjax says: before ajax command threw exception")}}var href=page.pageUrl;$.ajax({contentType:"application/json; charset="+Parameters.Charset,dataType:"json",url:href,timeout:30000,error:function(request,status,errorThrown){var errorStr="There was an error connecting to the page";
if(request.status==401){errorStr="Incorrect name/password combination"}$(_ajaxContainer).replaceWith('<div style="background:white;padding:8px"><h4>'+errorStr+'.</h4><br/><a  href="">Try Again</a></div>');
showPageContentOnViewPortImpl(false)},success:function(data,status,success){if(data.error_message){$(_ajaxContainer).replaceWith('<div style="background:white;padding:8px"><h4>'+data.error_message+'.</h4><br/><a  href="">Try Again</a></div>');
showPageContentOnViewPortImpl(false)}else{page.ajaxCallComplete=true;page.pageContent=data;_currentPage=page;showPageContentOnViewPortImpl()}}})}function getCacheSize(){if(_useLocalStorage){return localStorage.length
}else{var counter=0;for(var key in _cacheDB){counter++}return counter}}function showPageContentOnViewPortImpl(success){if($(_ajaxContainerTemp).length>0){$(_ajaxContainerTemp).remove()}if(success!=null&&!success){_frameworkReady=true;
setLoadingOnScreen(false);return false}if((_currentPage!=null)&&(_currentPage.pageContent!=null)&&($(_ajaxContainerTemp)!=null)&&(_currentPage.pageReady)){setLoadingOnScreen(false);if(_currentPage.pageContent.content.indexOf("document.write")!=-1){document.write=function(s){};
document.writeln=function(s){}}var newDiv=$(_currentPage.pageContent.content);newDiv.attr("ID",FIRST_CONTAINER_ID);$(_ajaxContainer).css("left","0px");try{$(_ajaxContainer).replaceWith(newDiv)}catch(e){}initAjaxLinks();
setHtmlParams(_currentPage);if(Parameters.AfterAjaxCommand!=null){try{Parameters.AfterAjaxCommand(_currentPage.pageContent)}catch(e){log("DMAjax says: after ajax command threw exception: "+e.message)}}if(typeof styleImages=="function"){styleImages();
if(!_.isUseLayout()){setTimeout("styleImages()",300);setTimeout("styleImages()",2000);setTimeout("styleImages()",5000)}}jQuery.DM.updateIOSHeight();try{if($("#shareSection").length>0||$(".dmShare").length>0){jQuery.getScript("http://platform.twitter.com/widgets.js");
IN.parse();if(gapi){gapi.plusone.go()}}}catch(e){log("DMAjax says: after ajax share reload threw exception: "+e.message)}try{var event=jQuery.Event("readystatechange");jQuery("document").trigger(event);
var event=jQuery.Event("onload");jQuery("window").trigger(event)}catch(e){log("DMAjax says: after ajax onload threw exception: "+e.message)}try{_.afterAjaxGeneralInits()}catch(e){log("DMAjax says: after ajax after ajax general inits threw exception: "+e.message)
}_frameworkReady=true;if(getCacheSize()<Parameters.CacheSize){addToCache(_currentPage)}_currentPage.scrollTo();createHistoryEntryForCurrentPage();try{if(_gaq!=null){dm_gaq_push_url(_currentPage.pageUrl)
}}catch(e){log("DMAjax says: gaq is not defined on dev mode, ignore this error")}}}function createHistoryEntryForCurrentPage(){if(Parameters.AllowAjax){if($.uaMatch(navigator.userAgent).browser!="msie"||($.uaMatch(navigator.userAgent).version>=8||document.documentMode>=8)){$.history.load(_currentPage.pageUrlIdentifier);
return false}}}function displayPage(page,showLoader,pushToStack){retrieveJqueryVar();buildQueueContainer();if(pushToStack==null){pushToStack=true}$(_ajaxContainerTemp).changeDisplay("block");$(_ajaxContainerTemp).css("position","absolute");
$(_ajaxContainerTemp).css("left",$(_ajaxContainer).offset().left+"px");$(_ajaxContainerTemp).css("top",$(_ajaxContainer).offset().top+"px");$(_ajaxContainerTemp).css("width",$(_ajaxContainer).outerWidth()+"px");
$(_ajaxContainerTemp).css("overflow","hidden");try{if(typeof("getInnerActiveAd")!="undefined"){getInnerActiveAd("ad","")}}catch(e){}if(page.linkType==Enum.LinkType.Home||page.pageAnimation=="backward"){_animationsArray[Parameters.AnimationTypeBackward].animateIn(page,showLoader)
}else{if(page.linkType==Enum.LinkType.Other||page.pageAnimation=="inner"){_animationsArray[Parameters.AnimationTypeInner].animateIn(page,showLoader)}else{if(page.linkType==Enum.LinkType.Nav||page.pageAnimation=="forward"||page.pageAnimation==null){_animationsArray[Parameters.AnimationTypeForward].animateIn(page,showLoader)
}}}if(pushToStack){_cacheStack.push(page.pageID)}else{_cacheStack.pop()}}function setHtmlParams(page){if(page.pageContent&&page.pageContent.url_redirect){window.location.href=page.pageContent.url_redirect;
return}if(page.pageContent==null){page.pageContent=_currentPage.pageContent}if(page.pageContent.css){if($.uaMatch(navigator.userAgent).browser!="msie"){$("#pagestyle").html(page.pageContent.css)}else{$("#pagestyle").get(0).styleSheet.cssText=page.pageContent.css
}}if($("#classic_link").length>0){if(page.pageContent.classic_link=="none"){$(".classicWrapper").hide()}else{$(".classicWrapper").show();$("#classic_link").attr("href",page.pageContent.classic_link)}}}function callbackAfterAnimation(event){$(event.target).off("webkitTransitionEnd transitionend msTransitionEnd oTransitionEnd");
_currentPage.pageReady=true;setLoadingOnScreen(true);scrollPage();showPageContentOnViewPortImpl()}function scrollPage(){if(isBrowserSupportTransitions()&&_userAgent!=Enum.AgentType.Android){var loader=$("#disabledImageZone:in-viewport");
if(loader.length==0){$("body, html").scrollTop(0)}}else{var loader=$("#loading:in-viewport");if(loader.length==0){$("body, html").scrollTop(0)}}}function noAnimation(){this.animateIn=function(page,showLoader){retrieveJqueryVar();
$(_ajaxContainer).html("");_currentPage.pageReady=true;setLoadingOnScreen(showLoader);scrollPage();showPageContentOnViewPortImpl()}}function SlideLeftAnimation(){this.animateIn=function(page){retrieveJqueryVar();
var wrapper=$(_wrappingContainer);if(Parameters.WebsiteGenerator!=Enum.WebPlatformType.Blogs){$(_ajaxContainer).css("overflow","hidden")}$(_ajaxContainer).css("opacity","1");$(_ajaxContainer).css("-webkit-transition","-webkit-transform 0.5s ease-out, opacity 0.5s linear");
$(_ajaxContainer).css("-webkit-transform","translate3d("+-wrapper.outerWidth()+"px, 0, 0)");$(_ajaxContainer).css("-moz-transition","-moz-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-moz-transform","translate("+-wrapper.outerWidth()+"px, 0)");
$(_ajaxContainer).css("-o-transition","-o-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-o-transform","translate("+-wrapper.outerWidth()+"px, 0px)");$(_ajaxContainer).css("-ms-transition","-ms-transform 0.5s ease-out, opacity 0.5s linear");
$(_ajaxContainer).css("-ms-transform","translate3d("+-wrapper.outerWidth()+"px, 0, 0)");document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("webkitTransitionEnd",callbackAfterAnimation,false);
document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("transitionend",callbackAfterAnimation,false);document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("oTransitionEnd",callbackAfterAnimation,false)
}}function SlideRightAnimation(){this.animateIn=function(page){retrieveJqueryVar();var wrapper=$(_wrappingContainer);if(Parameters.WebsiteGenerator!=Enum.WebPlatformType.Blogs){$(_ajaxContainer).css("overflow","hidden")
}$(_ajaxContainer).css("opacity","1");$(_ajaxContainer).css("-webkit-transition","-webkit-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-webkit-transform","translate3d("+wrapper.outerWidth()+"px, 0, 0)");
$(_ajaxContainer).css("-moz-transition","-moz-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-moz-transform","translate("+wrapper.outerWidth()+"px, 0)");$(_ajaxContainer).css("-o-transition","-o-transform 0.5s ease-out, opacity 0.5s linear");
$(_ajaxContainer).css("-o-transform","translate("+wrapper.outerWidth()+"px, 0px)");$(_ajaxContainer).css("-ms-transition","-ms-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-ms-transform","translate3d("+wrapper.outerWidth()+"px, 0, 0)");
document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("webkitTransitionEnd",callbackAfterAnimation,false);document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("transitionend",callbackAfterAnimation,false);
document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("oTransitionEnd",callbackAfterAnimation,false)}}function RotateAnimation(){this.animateIn=function(page){retrieveJqueryVar();if(Parameters.WebsiteGenerator!=Enum.WebPlatformType.Blogs){$(_ajaxContainer).css("overflow","hidden")
}$(_ajaxContainer).css("opacity","1");$(_ajaxContainer).css("-webkit-transform-style","preserve-3d");$(_ajaxContainer).css("-webkit-transition","-webkit-transform 0.4s ease-out, opacity 0.8s linear");$(_ajaxContainer).css("-webkit-transform","rotate3d(0,1,0,90deg)");
$(_ajaxContainer).css("-moz-transform-style","preserve-3d");$(_ajaxContainer).css("-moz-transition","-moz-transform 0.4s ease-out, opacity 0.8s linear");$(_ajaxContainer).css("-moz-transform","rotate(90deg)");
$(_ajaxContainer).css("-o-transform-style","preserve-3d");$(_ajaxContainer).css("-o-transition","-o-transform 0.4s ease-out, opacity 0.8s linear");$(_ajaxContainer).css("-o-transform","rotate(90deg)");
$(_ajaxContainer).css("-ms-transform-style","preserve-3d");$(_ajaxContainer).css("-ms-transition","-ms-transform 0.4s ease-out, opacity 0.8s linear");$(_ajaxContainer).css("-ms-transform","rotate3d(0,1,0,90deg)");
document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("webkitTransitionEnd",callbackAfterAnimation,false);document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("transitionend",callbackAfterAnimation,false);
document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("oTransitionEnd",callbackAfterAnimation,false)}}function FadeAnimation(){this.animateIn=function(page){retrieveJqueryVar();if(Parameters.WebsiteGenerator!=Enum.WebPlatformType.Blogs){$(_ajaxContainer).css("overflow","hidden")
}$(_ajaxContainer).css("opacity","1");$(_ajaxContainer).css("-webkit-transition","-webkit-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-webkit-transform","translate3d(0, 0, 0)");
$(_ajaxContainer).css("-moz-transition","-moz-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-moz-transform","translate(0, 0)");$(_ajaxContainer).css("-o-transition","-o-transform 0.5s ease-out, opacity 0.5s linear");
$(_ajaxContainer).css("-o-transform","translate(0px, 0px)");$(_ajaxContainer).css("-ms-transition","-ms-transform 0.5s ease-out, opacity 0.5s linear");$(_ajaxContainer).css("-ms-transform","translate3d(0, 0, 0)");
$(_ajaxContainer).css("opacity","0");document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("webkitTransitionEnd",callbackAfterAnimation,false);document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("transitionend",callbackAfterAnimation,false);
document.getElementById($(_ajaxContainer).attr("ID")).addEventListener("oTransitionEnd",callbackAfterAnimation,false)}}function setLoadingOnScreen(visible,pos,changeLoaderSize,keepColor){retrieveJqueryVar();
if(changeLoaderSize==null){changeLoaderSize=true}if(isBrowserSupportTransitions()&&_userAgent!=Enum.AgentType.Android){var loader=$("#disabledImageZone");if(loader.length>0){var body=$(_ajaxContainer);
if(body.length==0){body=$(_ajaxContainer)}if(visible){loader.css("position","absolute");loader.changeDisplay("block");loader.css("z-index","100000");if(pos==null){loader.css("left",(getPageWidth()/2)+"px");
loader.css("top",($(window).height()/2)+"px")}else{loader.css("left",pos[0]+"px");loader.css("top",pos[1]+"px")}if(changeLoaderSize){setLoaderSize(10,3)}if(!keepColor){assignLoaderColor()}}else{loader.changeDisplay("none")
}}}else{var body=$(_ajaxContainer);if(body.length==0){body=$(_ajaxContainer)}var loading=$("#loading");if(visible){if(loading.length==0){loading=$(document.createElement("div"));loading.attr("id","loading");
loading.css("background","url('/_dm/s/rt/images/w/nav-loader.gif') no-repeat center");loading.css("position","absolute");loading.css("z-index","100000");loading.css("width","43px");loading.css("height","40px");
body.parent().append(loading)}if(pos==null){loading.css("left",(body.width()/2-7)+"px");if(_userAgent==Enum.AgentType.Android){loading.css("left",(body.width()/2-28)+"px")}loading.css("top",(body.offset().top+20)+"px")
}else{loading.css("left",pos[0]+"px");loading.css("top",pos[1]+"px")}loading.changeDisplay("block")}else{if(loading.length>0){loading.changeDisplay("none")}}}}function assignLoaderColor(element){var elementBrigthness=255;
try{if(element==null){elementBrigthness=_.getScreenBrigthness()}else{elementBrigthness=_.getScreenBrigthness(element)}}catch(e){log("DMAjax says: unable to determine the screen brigthness, check background colors")
}if(elementBrigthness>125){setLoaderColor("rgb(0,17,17)")}else{setLoaderColor("rgb(255,238,238)")}}function findInCache(pageID){if(_useLocalStorage){return JSON.parse(_cacheDB.getItem(pageID))}else{return _cacheDB[pageID]
}}function findInCacheByUrl(pageUrl){try{for(var key in _cacheDB){if(_useLocalStorage){var urlFromJson=JSON.parse(_cacheDB.getItem(key)).pageUrl;if(urlFromJson==pageUrl){return JSON.parse(_cacheDB.getItem(key))
}}else{var fixedUrl=_cacheDB[key].pageUrl;if(_cacheDB[key].pageUrl.indexOf("?url=")!=-1){fixedUrl=unescape(getParamValue(_cacheDB[key].pageUrl,"url"))}if(fixedUrl==pageUrl){return _cacheDB[key]}}}}catch(e){return null
}return null}function addToCache(page){if(findInCache(page.pageID)==null){if(getCacheSize()<Parameters.CacheSize){if(_useLocalStorage){if(page.pageUrl.indexOf("url=")!=-1){page.pageUrl=unescape(getParamValue(page.pageUrl,"url"))
}else{page.pageUrl=unescape(page.pageUrl)}_cacheDB.setItem(page.pageID,JSON.stringify(page))}else{_cacheDB[page.pageID]=page}}}}function fixContainerBeforeTransition(container){_.collapseNavigation();var selectors="embed, a";
if(Parameters.SelectorsToHideOnTransitions!=null){selectors+=", "+Parameters.SelectorsToHideOnTransitions}container.find(selectors).each(function(index){if(this.nodeName=="a"||this.nodeName=="A"){$(this).unbind("click")
}else{$(this).remove()}});if($("#ad").length>0){}}function getPageScrollY(){var xScroll,yScroll;if(self.pageYOffset){yScroll=self.pageYOffset;xScroll=self.pageXOffset}else{if(document.documentElement&&document.documentElement.scrollTop){yScroll=document.documentElement.scrollTop;
xScroll=document.documentElement.scrollLeft}else{if(document.body){yScroll=document.body.scrollTop;xScroll=document.body.scrollLeft}}}return yScroll}function buildQueueContainer(){var newDiv=$('<div ID="'+SECOND_CONTAINER_ID+'"></div>');
var wrapper=$(_wrappingContainer);newDiv.css("position","absolute");newDiv.css("background-color","transparent");newDiv.css("top",$(_ajaxContainer).offset().top);newDiv.css("left",0+"px");newDiv.css("width",wrapper.outerWidth());
newDiv.css("height",$(_ajaxContainer).height()*2);newDiv.changeDisplay("block");var scroll=getPageScrollY()+0;var winHeight=getPageHeight()+0;var tot=scroll+winHeight+0;$(_ajaxContainer).css("height",tot+"px");
fixContainerBeforeTransition($(_ajaxContainer));newDiv.insertBefore($(_ajaxContainer))}function getPageScrollX(){var xScroll,yScroll;if(self.pageYOffset){yScroll=self.pageYOffset;xScroll=self.pageXOffset
}else{if(document.documentElement&&document.documentElement.scrollTop){yScroll=document.documentElement.scrollTop;xScroll=document.documentElement.scrollLeft}else{if(document.body){yScroll=document.body.scrollTop;
xScroll=document.body.scrollLeft}}}return xScroll}function getPageHeight(){return getWindowProp("innerHeight","clientHeight")}function getPageWidth(){return getWindowProp("innerWidth","clientWidth")}function getViewportScale(){return getPageWidth()/document.documentElement.clientWidth
}function callbackAfterSidebarChange(){var sidebar=$(Parameters.SidebarParams.SidebarSelector);if(sidebar.css("opacity")=="0"){sidebar.changeDisplay("none")}else{if(sidebar.css("opacity")=="1"){sidebar.changeDisplay("block")
}}}function getWindowProp(name,ie){try{if(window[name]!==undefined){return window[name]}var d=document.documentElement;if(d&&d[ie]){return d[ie]}if(document.body[ie]!=undefiened){return document.body[ie]
}else{if(name=="innerWidth"){return $("body").css("width").substr(0,$("body").css("width").length-2)}else{if(name=="innerHeight"){return $("body").css("width").substr(0,$("body").css("width").length-2)
}}}}catch(e){if(name=="innerWidth"){return $("body").css("width").substr(0,$("body").css("width").length-2)}else{if(name=="innerHeight"){return $("body").css("width").substr(0,$("body").css("width").length-2)
}}}}_.getCacheSize=function(){return getCacheSize()};_.getQueryParam=function(url,param){return getParamValue(url,param)};_.isUseLayout=function(){return $.layoutManager!=null};_.showPrevPageFromCache=function(){var page=getPrevCacheItem();
if(page!=null){page.pageAnimation="backward";page.show(false)}};function getPrevCacheItem(){try{var prevPage=null;var id=null;if(_cacheStack.length>1){id=_cacheStack[_cacheStack.length-2]}if(_useLocalStorage){prevPage=createPageFromCachedJson(JSON.parse(_cacheDB.getItem(id)))
}else{prevPage=_cacheDB[id]}return prevPage}catch(e){return null}}_.needToShowBackToHome=function(){Parameters.AllowAjax=Parameters.AllowAjax&&!($.DM.getQueryParam(window.location.href,"nee"));if(Parameters.AllowAjax){var show=_cacheStack.length>1;
if(_currentPage.pageContent){show=show&&!(_currentPage.pageContent.isHomePage)}return show}else{return !Parameters.IsCurrentHomePage}};function copyElementAttributes(source,destination,eraseOthers){if(eraseOthers==null){eraseOthers=false
}if(eraseOthers){for(var i=0;i<destination.get(0).attributes.length;i++){var a=destination.get(0).attributes[i];destination.removeAttr(a.name)}}for(var i=0;i<source.attributes.length;i++){var a=source.attributes[i];
destination.attr(a.name,a.value)}}_.restoreDefaultNavigationStyles=function(){var navContainer=$(Parameters.NavigationAreaParams.NavbarSelector);if(navContainer.length>0){var offsprings=navContainer.children("li:has(a):not(.dmHideFromNav)");
if(offsprings.length==0){offsprings=navContainer.children("a")}offsprings.each(function(index){var parent=$(this);if(this.nodeType==1){parent.css("position","");parent.css("top","");parent.changeDisplay("");
parent.css("opacity","");parent.css("-webkit-transition","");parent.css("-webkit-transform","");parent.css("-moz-transition","");parent.css("-moz-transform","");parent.css("-o-transition","");parent.css("-o-transform","");
parent.css("-ms-transition","");parent.css("-ms-transform","");parent.unbind("webkitTransitionEnd");parent.unbind("transitionend");parent.unbind("oTransitionEnd")}})}};_.loadExternalScriptsAsync=function(){loadExternalScriptAsync("/_dm/s/rt/scripts/jquery-viewport-plugin.js",null);
loadExternalScriptAsync("/_dm/s/rt/scripts/sha.js",null);var onLoadSwipes=null;if(Parameters.WebsiteGenerator==Enum.WebPlatformType.Blogs){onLoadSwipes=initBlogs}loadExternalScriptAsync("/_dm/s/rt/scripts/jquery.touchSwipe-1.2.4.js",onLoadSwipes);
loadExternalScriptAsync("/_dm/s/rt/scripts/jquery-history.js",initHistory)};_.initNavbar=function(forceInit){if(forceInit==null){forceInit=false}if(!_frameworkReady||forceInit){var navContainer=$(Parameters.NavigationAreaParams.NavbarSelector);
var newNavContainer=$(".newNavigationElementPlaceHolder");isNewNav=false;if(newNavContainer.length>0){Parameters.NavigationAreaParams.NavbarSelector=".newNavigationElementPlaceHolder #dmNav";isNewNav=true
}if(isNewNav){initialCollapseNavigation()}else{if(navContainer.length>0){if(_currentPage.linkType==Enum.LinkType.Home||(_currentPage.pageContent!=null&&typeof(_currentPage.pageContent.isHomePage)!=undefined&&_currentPage.pageContent.isHomePage)||(_currentPage.pageContent==null&&_.isCurrentHomePage())){navContainer.changeDisplay("block",true);
initialCollapseNavigation();_.initSubNavbar()}else{if(Parameters.NavigationAreaParams.ShowBackToHomeOnInnerPages&&_currentPage.pageContent!=null&&_currentPage.pageContent.alias==Parameters.DefaultPageAlias&&!isNewNav){navContainer.css("cssText","display: none !important");
showBackToHome();_.initSubNavbar();$(".dm_subMenu").each(function(index){$(this).changeDisplay("block",true)})}else{if(_currentPage.pageContent==null&&!_.isCurrentHomePage()){navContainer.changeDisplay("none");
showBackToHome();_.initSubNavbar();$(".dm_subMenu").each(function(index){$(this).changeDisplay("block",true)})}else{navContainer.changeDisplay("block",true);initialCollapseNavigation()}}}}else{if(!isNewNav&&_currentPage.linkType!=Enum.LinkType.Home&&(typeof(_currentPage.pageContent.isHomePage)==undefined||!_currentPage.pageContent.isHomePage)&&Parameters.NavigationAreaParams.ShowBackToHomeOnInnerPages&&($("#dmPostBackToMain").length>0||_currentPage.pageContent.alias==Parameters.DefaultPageAlias)){showBackToHome();
_.initSubNavbar()}}}}};_.initSubNavbar=function(){var subNavContainer=$(Parameters.NavigationAreaParams.SubNavbarSelector);if(subNavContainer.length>0){initialCollapseNavigation(true)}};_.hangEventsOnMoreLess=function(callback){if(callback){afterExpCol=callback
}};_.expandNavigation=function(isSubNavigation){if(isSubNavigation==null){isSubNavigation=false}var navContainer=$(Parameters.NavigationAreaParams.NavbarSelector);var threshold=Parameters.NavigationAreaParams.NavbarSize;
if(isSubNavigation){navContainer=$(Parameters.NavigationAreaParams.SubNavbarSelector)}var firstLevelUl=navContainer;if(firstLevelUl.length>0){var moreObj=firstLevelUl.find(".dmMore");if(moreObj.length==0){moreObj=firstLevelUl.find(".dmNavigationMoreAnchor")
}if(moreObj.length>0){moreObj.remove();var btnLess=createLastNavButton(navContainer,"less",isSubNavigation);firstLevelUl.append(btnLess);var height=0;var lessMenuHeight=0;var savedHeight=0;var spacer=0;
var offsprings=navContainer.children("li:has(a):not(.dmHideFromNav)");if(offsprings.length==0){offsprings=navContainer.children("a")}offsprings.each(function(index){var parent=$(this);if(this.nodeType==1&&index==0){spacer=parent.offset().top;
savedHeight=parent.height()}else{if(this.nodeType==1&&index==1){spacer=(parent.offset().top-spacer-savedHeight)}}if(this.nodeType==1&&index>=threshold){height=parseInt(height,10)+parseInt(parent.height(),10);
height+=spacer}});var p=-height+spacer;var btnHeight=btnLess.height();var firstItem;var displayValue="";offsprings.each(function(index){var parent=$(this);if(index==0){firstItem=parent.clone().css("display",parent.css("display"))
}if(this.nodeType==1&&index==threshold-1){savedHeight=parent.height();displayValue=parent.css("display")}else{if(this.nodeType==1&&index>=threshold){if(!parent.hasClass("dmNavigationLessAnchor")&&!parent.hasClass("dmLess")){height=parent.height();
var place=lessMenuHeight+savedHeight+spacer;lessMenuHeight+=savedHeight+spacer;savedHeight=height;parent.removeClass("p_list_last");parent.addClass("p_list_item");parent.changeDisplay(displayValue);if(allowNavAnimations(firstLevelUl,firstItem)){parent.css("-webkit-transition","-webkit-transform 0.2s linear, opacity 0.4s linear");
parent.css("-webkit-transform","translate3d(0, "+place+"px, 0)");parent.css("opacity","1");parent.css("-moz-transition","-moz-transform 0.2s linear, opacity 0.4s linear");parent.css("-moz-transform","translate(0, "+place+"px)");
parent.css("-o-transition","-o-transform 0.2s linear, opacity 0.4s linear");parent.css("-o-transform","translate(0px, "+place+"px)");parent.css("-ms-transition","-ms-transform 0.2s linear, opacity 0.4s linear");
parent.css("-ms-transform","translate(0, "+place+"px)");var endTrans=function(){parent.changeDisplay(displayValue)};parent.bind("webkitTransitionEnd",endTrans);parent.bind("transitionend",endTrans);parent.bind("oTransitionEnd",endTrans)
}}else{height=parent.height();var place=lessMenuHeight+height+spacer;lessMenuHeight+=height;parent.addClass("p_list_item");parent.changeDisplay(displayValue);if(allowNavAnimations(firstLevelUl,firstItem)){if(!isSpecialBrowser()&&!$.browser.opera){btnLess.css("top",p-btnHeight+"px")
}else{btnLess.css("top","0px")}if(!isSpecialBrowser()){btnLess.css("top",-place+"px")}parent.css("-webkit-transition","-webkit-transform 0.2s linear, opacity 0.4s linear");parent.css("-webkit-transform","translate3d(0, "+place+"px, 0)");
parent.css("opacity","1");parent.css("-moz-transition","-moz-transform 0.2s linear, opacity 0.4s linear");parent.css("-moz-transform","translate(0, "+place+"px)");parent.css("-o-transition","-o-transform 0.2s linear, opacity 0.4s linear");
parent.css("-o-transform","translate(0px, "+place+"px)");parent.css("-ms-transition","-ms-transform 0.2s linear, opacity 0.4s linear");parent.css("-ms-transform","translate3d(0, "+place+"px, 0)");var endTrans=function(){parent.changeDisplay(displayValue)
};parent.bind("webkitTransitionEnd",endTrans);parent.bind("transitionend",endTrans);parent.bind("oTransitionEnd",endTrans)}}}}})}if($.browser.msie){firstLevelUl.changeDisplay("none",true);firstLevelUl.changeDisplay("block",true)
}else{if(displayValue=="inline-block"){firstLevelUl.hide();firstLevelUl.show()}}var fix=false;firstLevelUl.find("li").each(function(key,value){var li=$(this);if(li.css("display")=="inline-block"){fix=true;
li.css("display","inline")}});if(fix){firstLevelUl.find("li").each(function(key,value){var li=$(this);li.css("display","inline-block")})}}};_.fullCollapseNavigation=function(isSubNavigation){initialCollapseNavigation(isSubNavigation)
};_.collapseNavigation=function(isSubNavigation){if(isSubNavigation==null){isSubNavigation=false}var navContainer=$(Parameters.NavigationAreaParams.NavbarSelector);var threshold=Parameters.NavigationAreaParams.NavbarSize;
if(isSubNavigation){navContainer=$(Parameters.NavigationAreaParams.SubNavbarSelector)}var firstLevelUl=navContainer;if(firstLevelUl.length>0){var lessObj=firstLevelUl.find(".dmLess");if(lessObj.length==0){lessObj=firstLevelUl.find(".dmNavigationLessAnchor")
}var firstItem;if(lessObj.length>0){lessObj.remove();var totalHeight=0;var btnMore=createLastNavButton(navContainer,"more",isSubNavigation);firstLevelUl.append(btnMore);var offsprings=navContainer.children("li:has(a):not(.dmHideFromNav)");
if(offsprings.length==0){offsprings=navContainer.children("a")}offsprings.each(function(index){var parent=$(this);if(index==0){firstItem=parent.clone().css("display",parent.css("display"))}if(index<=threshold&&this.nodeType==1){totalHeight+=parent.height()
}if(this.nodeType==1&&index>=threshold){if(!parent.hasClass("dmNavigationMoreAnchor")&&!parent.hasClass("dmMore")){parent.css("position","relative");parent.removeClass("p_list_last");parent.addClass("p_list_item");
parent.changeDisplay("none");if(allowNavAnimations(firstLevelUl,firstItem)){parent.css("-webkit-transition","");parent.css("-webkit-transform","");parent.css("opacity","0");parent.css("-moz-transition","");
parent.css("-moz-transform","");parent.css("-o-transition","");parent.css("-o-transform","");parent.css("-ms-transition","");parent.css("-ms-transform","");var endTrans=function(){parent.changeDisplay("none")
};parent.bind("webkitTransitionEnd",endTrans);parent.bind("transitionend",endTrans);parent.bind("oTransitionEnd",endTrans)}}}})}if($.uaMatch(navigator.userAgent).browser=="msie"){firstLevelUl.changeDisplay("none",true);
firstLevelUl.changeDisplay("block",true)}}};function equalHeight(group){tallest=0;group.each(function(){thisHeight=jQuery(this).height();if(thisHeight>tallest){tallest=thisHeight}});group.css("min-height",tallest+"px")
}_.initTabs=function(){jQuery(".dmtab").live("click",function(event){$(this).parent().find(".dmtab").removeClass("active");$(this).addClass("active");$(this).parent().parent().find(".dmtabscont > div").hide();
$(this).parent().parent().find(".dmtabscont > div").dmCss("display","none !important");$(this).parent().parent().find(".dmtabscont >div:eq("+$(this).index()+")").show();$(this).parent().parent().find(".dmtabscont >div:eq("+$(this).index()+")").dmCss("display","block !important");
if(!$(this).is(":in-viewport")){_.jumpTo(jQuery(this),-100)}});jQuery(".dmtabsheader > div").removeClass("active");jQuery(".dmtabsheader > div:first-child").addClass("active");jQuery(".dmtabscont > div").hide();
jQuery(".dmtabscont > div").css("display","none !important");jQuery(".dmtabscont > div:first-child").show();jQuery(".dmtabscont > div:first-child").dmCss("display","block !important");jQuery(".dmtabs.shapeSimpleLeft .dmtabscont > div, .dmtabs.shapeSimpleRight .dmtabscont > div").css("min-height",function(){return jQuery(this).closest(".dmtabs").find(".dmtabsheader").height()+"px"
})},_.ajaxExt=function(){$("[ext_ajax_load]").each(function(){var pageId=$(this).attr("ext_page_id");var extId=$(this).attr("dmle_extension");var elementId=$(this).attr("ext_el_id");var _this=$(this);$.post("/_dm/s/rt/scripts/ajax_ext.jsp",{pageId:pageId,extId:extId,elementId:elementId},function(data){_this.replaceWith(data)
})})},_.initForm=function(){jQuery(".dmform form").unbind("submit").submit(function(event){var _this=$(this);event.preventDefault();_this.closest(".dmform").find(".dmform-error").hide();$(".inputError").removeClass("inputError");
var passedValidation=true;_this.find(".required input, .required textarea").each(function(index,input){if($(input).val().trim()==""){$(input).addClass("inputError");if(passedValidation){_.jumpTo(input,-20)
}passedValidation=false}});if(!passedValidation){return}dm_gaq_push_event("form","submit");var loaderY=_this.find("input[type='submit']").offset().top-100;var loaderX=(getPageWidth()/2);var pos=[loaderX,loaderY];
_.setLoadingOnScreen(true,pos);var loop=0;_this.closest(".dmform").find("input, textarea, select").map(function(){var child=$(this);var name=child.attr("name");if(name&&name.startsWith("dmform-")){var index=loop;
if(index<10){index="0"+index}child.closest(".dmforminput").find("input[type=hidden]").attr("name","label-dmform-"+index);child.attr("name","dmform-"+index);if(!child.is("[type=radio]")||child.parent().is(":last-child")){loop++
}}});$.post("/runtime/nee.form.submit.jsp",$(this).serialize(),function(data){var successPage=_this.closest(".dmform").find(".dmform-success").data("success-page");if(successPage){location.replace(successPage);
return}_this.closest(".dmform-wrapper").hide();_this.closest(".dmform").find(".dmform-success").show();_.jumpTo(_this.closest(".dmform").find(".dmform-success"),-100);_.setLoadingOnScreen(false)}).error(function(){_this.closest(".dmform").find(".dmform-error").show();
_.jumpTo(_this.closest(".dmform").find(".dmform-error"),-100);_.setLoadingOnScreen(false)})});$(".inputError").live("keypress",function(){$(this).removeClass("inputError")})},_.initImageSlider=function(isRefresh,options){if(jQuery(".dmImageSlider").length>0){loadExternalScriptAsync("/_dm/s/rt/scripts/flexSlider/jquery.flexslider.js",initImageSliderImp)
}function initImageSliderImp(){var elemToReplace=null;var allSliders=jQuery(".dmImageSlider");var mySlider=null;var firstSlide=0;var defaultParams={directionNav:true,start:function(slider){mySlider=slider;
var isSlides=slider.find(".slides li").length>0?true:false;if(!isSlides){slider.find(".slides").attr("style","")}mySlider.pause();if(elemToReplace){elemToReplace.find(".flexslider").replaceWith(mySlider)
}for(var i=0;i<mySlider.find("li").length;i++){var tempLi=$(mySlider.find("li")[i]);var liImg=tempLi.find("img");if(liImg.length>0){var imgBorderWidth=parseInt(liImg.css("border-left-width"));var opts={stretch:initAttr.stretch,forceContainerWidth:(mySlider.width()-imgBorderWidth*2),forceContainerHeight:(mySlider.height()-imgBorderWidth*2)};
tempLi.css("width",$(window).width()+"px");var centeredImg=liImg.centerImageWithin(mySlider,opts);if(!centeredImg){liImg.unbind("load").load(function(){$(this).centerImageWithin(mySlider,opts)})}}}if(isRefresh){if(options.isFromAdd){firstSlide=slider.count-1
}else{if(options.stayCurrSlide){firstSlide=options.stayCurrSlide}}slider.flexAnimate(firstSlide,false)}if(initAttr.isAutoPlay){slider.resume()}},before:function(slider){if(options&&options.start){options.start(slider,options)
}}};var _restoreElem=function(elem){elem.find(".flex-control-nav").remove();elem.find(".flex-direction-nav").remove();elem.find(".flex-pauseplay").remove();elem.find(".clone").remove();elem.find(".flexslider img").removeAttr("style");
elem.find(".slides").removeAttr("style");elem.find(".slides li").removeAttr("style");elem.find(".flexslider p").removeAttr("style")};for(var i=0;i<allSliders.length;i++){var thisElem=$(allSliders[i]);var initAttr=thisElem.find(".flexslider").attr("sliderScriptParams");
initAttr=eval("("+initAttr+")");initAttr=$.extend({},defaultParams,initAttr);if(initAttr.animation==true){initAttr.animation="slide"}else{initAttr.animation="fade"}if(thisElem.find(".flexslider").find(".slides li:not(.clone)").size()==1){initAttr.directionNav=false
}if(isRefresh){if(thisElem.find(".flexslider").attr("duda_id")===options.elemId){thisElem.find(".flexslider").data().flexslider=false;elemToReplace=thisElem;thisElem=thisElem.clone(true);if(options.isFromAdd){initAttr.slideToStart=thisElem.find(".flexslider").find(".slides li").size()-1;
if(initAttr.slideToStart<0){initAttr.slideToStart=0}}else{if(options.stayCurrSlide){initAttr.slideToStart=parseInt(options.stayCurrSlide)}}thisElem.find(".flexslider").flexslider(initAttr)}}else{_restoreElem(thisElem.find(".flexslider"));
thisElem.find(".flexslider").data().flexslider=false;thisElem.find(".flexslider").flexslider(initAttr)}}}},_.initRSS=function(){var descs=$(".dmRSSFeed .dmListItemDescriptionDiv");descs.each(function(){var $el=$(this);
var curHeight=$el.height();$el.css("max-height","none");if($el.height()==curHeight){$el.parent().find(".rssListReadMore").addClass("dmDisplay_None")}else{$el.parent().find(".rssListReadMore").removeClass("dmDisplay_None")
}$el.css("max-height","")})},_.initPhotoGallery=function(){if(jQuery(".dmPhotoGallery").length>0){loadExternalScriptAsync("/_dm/s/rt/scripts/photoSwipe/klass.min.js",initPhotoGalleryImpl)}function initPhotoGalleryImpl(){jQuery(".photoGalleryViewAll").unbind("click").click(function(event){var _this=$(this);
var thisGal=_this.closest(".dmPhotoGallery");var initAttr=thisGal.attr("galleryOptionsParams");initAttr=eval("("+initAttr+")");var _numToShow=initAttr.thumbnailsPerRow*initAttr.rowsToShow;_numToShow-=1;
if(_this.attr("isAll")=="true"){_this.attr("isAll","false");_this.html("view less");thisGal.find("li").show()}else{_this.attr("isAll","true");_this.html("view all");thisGal.find("li:gt("+_numToShow+")").hide()
}});var allGallery=jQuery(".dmPhotoGallery");for(var i=0;i<allGallery.length;i++){var defaultParams={enableMouseWheel:false,enableKeyboard:false};var thisGal=$(allGallery[i]);var initAttr=thisGal.attr("galleryOptionsParams");
initAttr=eval("("+initAttr+")");initAttr=$.extend({},defaultParams,initAttr);initAttr.imageScaleMethod="fitNoUpscale";initAttr.allowUserZoom=false;if(thisGal.find("li").length>0){_initImagesSizeForGallery=function(thisGal,initAttr){var liList=thisGal.find("li");
var contSize=initAttr.thumbnailsPerRow==2?130:(initAttr.thumbnailsPerRow==3?80:59);var opts={stretch:true,forceContainerWidth:contSize,forceContainerHeight:contSize};for(var j=0;j<liList.length;j++){var centeredImg=$(liList[j]).find("img").centerImageWithin(thisGal,opts);
if(!centeredImg){$(liList[j]).find("img").unbind("load").load(function(){$(this).centerImageWithin(thisGal,opts);$(this).addClass("galleryImgInside")})}}};_initImagesSizeForGallery(thisGal,initAttr);var numToShow=initAttr.thumbnailsPerRow*initAttr.rowsToShow;
var allLiElem=thisGal.find("li").length;thisGal.find("li").hide();thisGal.find("li:lt("+numToShow+")").show();if(allLiElem>numToShow){thisGal.find(".photoGalleryViewAll").show();thisGal.find(".photogalleryviewall").addClass("photoGalleryViewAll").show()
}else{thisGal.find(".photoGalleryViewAll").hide();thisGal.find(".photogalleryviewall").hide()}var isNeeEditor=window.location.href.indexOf("nee=")!=-1;if(!isNeeEditor){var myPhotoSwipe=thisGal.find(".gallery a").photoSwipe(initAttr)
}}}}},_.initTwitterFeed=function(options){if(jQuery(".dmTwitterFeed").length>0){loadExternalScriptAsync("http://widgets.twimg.com/j/2/widget.js",initTwitterFeedImpl)}function initTwitterFeedImpl(){var placFeed=jQuery(".dmTwitterFeed");
for(var i=0;i<placFeed.length;i++){var thisFeed=$(placFeed[i]);var twitterType=thisFeed.attr("twitterType");var username=thisFeed.attr("twitterUserName");var numOfTweet=thisFeed.attr("numberOfTweets");
var isScrollable=numOfTweet>3?true:false;_tempDocumentWrite=document.write;document.write=function(markup){thisFeed.html(markup)};var data={version:2,interval:30000,width:"auto",height:220,theme:{shell:{background:"transparent",color:"#ffffff"},tweets:{background:"transparent",color:"#ffffff",links:"#4AED05"}},};
if(twitterType=="Profile"){new TWTR.Widget($.extend(data,{type:"profile",rpp:numOfTweet,features:{scrollbar:isScrollable,loop:false,live:false,behavior:"all"}})).render().setUser(username).start()}else{if(twitterType=="Search"){new TWTR.Widget($.extend(data,{type:"search",search:thisFeed.attr("searchQuery"),title:thisFeed.attr("twitterTitle"),subject:thisFeed.attr("twitterCaption"),features:{scrollbar:true,loop:false,live:false,behavior:"all"}})).render().start()
}else{new TWTR.Widget($.extend(data,{type:"faves",rpp:5,title:thisFeed.attr("twitterTitle"),subject:thisFeed.attr("twitterCaption"),features:{scrollbar:true,loop:false,live:false,behavior:"all"}})).render().setUser(username).start()
}}if(_tempDocumentWrite!=null){document.write=_tempDocumentWrite}}options&&options.callback()}},_.preloadImages=function(options){var tmpImage=new Image();tmpImage.src="/_dm/s/rt/images/emailShareTitleBg.png";
tmpImage.src="/_dm/s/rt/images/closeShareWin.png"},_.initSidebar=function(){var sidebar=$(Parameters.SidebarParams.SidebarSelector);var arrow=$(Parameters.SidebarParams.SidebarArrowSelector);var blockContainer=$(Parameters.NavigationAreaParams.BlockContainerSelector);
if(isSidebarEmpty()){if(arrow.length>0){arrow.parentNode.removeChild(arrow)}return}if(arrow.length==0){var arrow=$("<a></a>");arrow.attr("id",Parameters.SidebarParams.SidebarArrowSelector.substr(1));arrow.addClass("fw-sidebar-arrow");
arrow.attr("tabindex","1");arrow.attr("href","javascript: void(0)");arrow.unbind("click").click(_.openSideBar);arrow.css("outline","none");blockContainer.prepend(arrow)}sidebar.css("opacity","0");sidebar.changeDisplay("none");
sidebar.css("-webkit-transition","-webkit-transform 0.4s linear, opacity 0.4s linear");sidebar.css("-moz-transition","-moz-transform 0.4s linear, opacity 0.4s linear");sidebar.css("-o-transition","-o-transform 0.4s linear, opacity 0.4s linear");
sidebar.css("-ms-transition","-ms-transform 0.4s linear, opacity 0.4s linear");sidebar.css("-webkit-transform-origin","100% 0%");sidebar.css("-moz-transform-origin","100% 0%");sidebar.css("-o-transform-origin","100% 0%");
sidebar.css("-ms-transform-origin","100% 0%");sidebar.css("-webkit-transform","scale3d(0,0,0)");sidebar.css("-moz-transform","scale(0,0)");sidebar.css("-o-transform","scale(0,0)");sidebar.css("-ms-transform","scale3d(0,0,0)");
document.getElementById(sidebar.attr("ID")).addEventListener("webkitTransitionEnd",callbackAfterSidebarChange,false)};_.openSideBar=function(){var sidebar=$(Parameters.SidebarParams.SidebarSelector);var arrow=$(Parameters.SidebarParams.SidebarArrowSelector);
if(sidebar.length>0&&arrow.length>0){arrow.addClass("fw-sidebar-arrow-close");arrow.removeClass("fw-sidebar-arrow");arrow.unbind("click").click(_.closeSideBar);$(Parameters.NavigationAreaParams.BlockContainerSelector).css("position","relative");
sidebar.css("top","0px");sidebar.changeDisplay("block");sidebar.css("opacity","0");if(isBrowserSupportTransitions()){sidebar.css("right",(0-($(document).width()-$(window).width()))+"px")}sidebar.css("-webkit-transform","scale3d(1,1,1)");
sidebar.css("-moz-transform","scale(1,1)");sidebar.css("-o-transform","scale(1,1)");sidebar.css("-ms-transform","scale3d(1,1,1)");sidebar.css("opacity","1");$("#fw-bigcontain embed, #fw-bigcontain object").changeDisplay("none")
}};_.closeSideBar=function(){var sidebar=$(Parameters.SidebarParams.SidebarSelector);var arrow=$(Parameters.SidebarParams.SidebarArrowSelector);if(sidebar.length>0&&arrow.length>0){arrow.addClass("fw-sidebar-arrow");
arrow.removeClass("fw-sidebar-arrow-close");arrow.click(_.openSideBar);sidebar.css("-webkit-transform","scale3d(0,0,0)");sidebar.css("-moz-transform","scale(0,0)");sidebar.css("-o-transform","scale(0,0)");
sidebar.css("-ms-transform","scale3d(0,0,0)");sidebar.css("opacity","0");if($.uaMatch(navigator.userAgent).browser=="msie"||$.uaMatch(navigator.userAgent).browser=="opera"||!isBrowserSupportTransitions()){sidebar.changeDisplay("none")
}$("#fw-bigcontain embed, #fw-bigcontain object").changeDisplay("block")}};_.hasSideBar=function(){var arrow=$(Parameters.SidebarParams.SidebarArrowSelector);if(arrow.length==0){return false}else{return true
}};_.afterAjaxGeneralInits=function(){_.loadExternalScriptsAsync();_.initNavbar();_.initSidebar();_.initTabs();_.initForm();_.initImageSlider();_.initRSS();_.initPhotoGallery();_.initTwitterFeed();_.ajaxExt()
};_.displayGalleryModuleImage=function(imageSrc){var loaderY=getPageScrollY()+(getPageHeight()/2)-50;var loaderX=(getPageWidth()/2);var pos=[loaderX,loaderY];setLoadingOnScreen(true,pos);var module=$("#"+GALLERY_CONTAINER_ID);
module.html("");var moduleImage=$('<img ID="'+GALLERY_CONTAINER_ID_IMG+'" onclick="jQuery.DM.blackScreen(false); jQuery.DM.ClearGalleryModule();" ontouchmove="touchMove(event);"></img>');moduleImage.changeDisplay("none");
moduleImage.css("border","2px solid #FFFFFF");module.append(moduleImage);var pic_real_width=null;var pic_real_height=null;var picScaleFactor=0.85;if(moduleImage.length>0){moduleImage.attr("src",imageSrc).load(function(){pic_real_width=this.width;
pic_real_height=this.height;moduleImage.data("originalWidth",pic_real_width);moduleImage.data("originalHeight",pic_real_height);var s=Math.min(getViewportScale(),Math.min(getPageHeight()/pic_real_height,getPageWidth()/pic_real_width));
s=s*picScaleFactor;moduleImage.width(Math.round(pic_real_width*s));moduleImage.height(Math.round(pic_real_height*s));module.css({top:getPageScrollY()*1+((getPageHeight()-moduleImage.height()*1)/2)-8+"px",left:Math.round((getPageWidth()-moduleImage.width())/2)+"px"}).width(Math.round(moduleImage.width()));
module.changeDisplay("block");moduleImage.changeDisplay("block");var closeButton=$('<div ID="closeImageModule" onclick="jQuery.DM.blackScreen(false); jQuery.DM.ClearGalleryModule();">close</div>');closeButton.css("color","#000000");
closeButton.css("background-color","#FFFFFF");closeButton.css("text-align","center");closeButton.css("font-family","Arial");closeButton.css("font-size","13px");closeButton.css("margin-top","10px");closeButton.css("-moz-border-radius","8px");
closeButton.css("border-radius","8px");closeButton.css("border","1px solid #333333");closeButton.css("margin-left","auto");closeButton.css("margin-right","auto");closeButton.css("cursor","pointer");closeButton.width(40);
closeButton.height(17);module.append(closeButton);setLoadingOnScreen(false);_.blackScreen(true)})}};_.ClearGalleryModule=function(){var module=$("#"+GALLERY_CONTAINER_ID);if(module.length>0){module.html("")
}};_.getScreenBrigthness=function(elementSelector){var background=$(Parameters.BackgroundElement);if(elementSelector!=null){background=$(elementSelector)}if(background!=null){var rgb=background.css("background-color");
if(rgb==null){return 255}if(rgb.indexOf("rgba")==-1){var re=/rgb\((\d+), (\d+), (\d+)\)/;rgb=re.exec(rgb);var r=parseInt(rgb[1],10);var g=parseInt(rgb[2],10);var b=parseInt(rgb[3],10);var brigthness=(r*299+g*587+b*114)/1000;
return brigthness}else{var re=/rgba\((\d+), (\d+), (\d+), (\d+)\)/;rgb=re.exec(rgb);var r=parseInt(rgb[1],10);var g=parseInt(rgb[2],10);var b=parseInt(rgb[3],10);var a=parseInt(rgb[4],10);var brigthness=(r*299+g*587+b*114)/1000;
if(a==0){brigthness=255}return brigthness}}else{return 255}};_.logToDMAjax=function(message){log(message)};_.initSwipeSelectors=function(selector,swipeLeftHandler,swipeRightHandler){var onload=function(){$(selector).each(function(){var jqueryElement=$(this);
var keepMoved=jqueryElement.attr("keep-moved")!=null;jqueryElement.css("position","relative");jqueryElement.css("-webkit-transition","-webkit-transform 0.1s ease-out");jqueryElement.css("-webkit-backface-visibility","hidden");
jqueryElement.css("-webkit-transform","translate3d(0, 0, 0)");var moved=0;var minDistance=40;if(jqueryElement.attr("min-distance")!=null){minDistance=parseInt(jqueryElement.attr("min-distance"))}var maxWidth=jqueryElement.width()-100;
var preserveMax=jqueryElement.attr("preserve-max")!=null;var swipePhasesHandler=function(event,phase,direction,distance){if(phase=="start"){if(keepMoved&&jqueryElement.attr("moved")!=null){moved=parseInt(jqueryElement.attr("moved"))
}}else{if(phase=="move"){if(direction=="right"&&distance>minDistance){var movePosition=moved+distance;if(preserveMax&&movePosition>0){movePosition=0}jqueryElement.css("-webkit-transform","").css("-webkit-transform","translate3d("+(movePosition)+"px, 0, 0)");
if(keepMoved){jqueryElement.attr("moved",(movePosition))}event.preventDefault()}else{if(direction=="left"&&distance>minDistance){var movePosition=moved-distance;if(preserveMax&&movePosition<(-maxWidth)){movePosition=-maxWidth
}jqueryElement.css("-webkit-transform","").css("-webkit-transform","translate3d("+(movePosition)+"px, 0, 0)");if(keepMoved){jqueryElement.attr("moved",(movePosition))}event.preventDefault()}}}else{if(phase=="end"){if(direction=="right"){if(!swipeRightHandler()){jqueryElement.css("-webkit-transform","translate3d("+(moved+0)+"px, 0, 0)")
}}else{if(direction=="left"){if(!swipeLeftHandler()){jqueryElement.css("-webkit-transform","translate3d("+(moved+0)+"px, 0, 0)")}}}}else{if(phase=="cancel"){jqueryElement.css("-webkit-transform","translate3d("+(moved+0)+"px, 0, 0)")
}}}}};var params={triggerOnTouchEnd:true,swipeStatus:swipePhasesHandler};jqueryElement.swipe(params)})};loadExternalScriptAsync("/_dm/s/rt/scripts/jquery.touchSwipe-1.2.4.js",onload)};_.getCurrentPageUrl=function(){var pageUrl=_currentPage.pageUrl;
if(pageUrl.indexOf("url=")!=-1){pageUrl=unescape($.DM.getQueryParam(_currentPage.pageUrl,"url"))}return pageUrl};_.getPageUrlByPageId=function(pageID){if(pageID!=null){var p=findInCache(pageID);if(p!=null){var pageUrl=p.pageUrl;
if(pageUrl.indexOf("url=")!=-1){pageUrl=pageUrl.substr(0,pageUrl.indexOf("url="))}return pageUrl}}return null};function initialCollapseNavigation(isSubNavigation){if(isSubNavigation==null){isSubNavigation=false
}var navContainer=$(Parameters.NavigationAreaParams.NavbarSelector);var threshold=Parameters.NavigationAreaParams.NavbarSize;if(isSubNavigation){navContainer=$(Parameters.NavigationAreaParams.SubNavbarSelector)
}var firstLevelUl=navContainer;if(firstLevelUl.length>0){var offsprings=navContainer.children("li:has(a):not(.dmHideFromNav)");if(offsprings.length==0){offsprings=navContainer.children("a")}if(offsprings.eq(0).css("display")=="inline"&&offsprings.eq(0).children(":first-child").css("display")!="block"){firstLevelUl.length=0;
return}var lessObj=firstLevelUl.find(".dmLess");if(lessObj.length==0){lessObj=firstLevelUl.find("#dmNavigationLessAnchor")}if(lessObj.length>0){lessObj.remove()}var moreObj=firstLevelUl.find(".dmMore");
if(moreObj.length==0){moreObj=firstLevelUl.find("#dmNavigationMoreAnchor")}if(moreObj.length>0){moreObj.remove()}var needToAddMoreButton=false;var height=0;var spacer=0;var lastHeight=0;var nodesCounter=0;
var displayValue="block";var firstItem;var offsprings=navContainer.children("li:has(a):not(.dmHideFromNav)");if(offsprings.length==0){offsprings=navContainer.children("a")}if(offsprings.length>threshold+1){offsprings.each(function(index){var parent=$(this);
if(this.nodeType==1){if(index==0){if(parent.css("display")=="inline-block"){displayValue=parent.css("display")}firstItem=parent.clone().css("display",parent.css("display"))}if(!(isIE8()||isIE7())){}if(index>=threshold){nodesCounter++;
if(isSpecialBrowser()){parent.changeDisplay("none");parent.removeClass("p_list_last")}else{if(index==threshold){spacer=(parent.offset().top-spacer-lastHeight);height+=lastHeight+spacer}parent.changeDisplay("none");
parent.css("position","relative");parent.removeClass("p_list_last");if(!parent.hasClass("dmNavigationMoreAnchor")&&!parent.hasClass("dmMore")){parent.css("position","relative");parent.removeClass("p_list_last");
parent.addClass("p_list_item");parent.changeDisplay("none");if(allowNavAnimations(firstLevelUl,firstItem)){parent.css("-webkit-transition","");parent.css("-webkit-transform","");parent.css("opacity","0");
parent.css("-moz-transition","");parent.css("-moz-transform","");parent.css("-o-transition","");parent.css("-o-transform","");parent.css("-ms-transition","");parent.css("-ms-transform","");var endTrans=function(){parent.changeDisplay("none")
};parent.bind("webkitTransitionEnd",endTrans);parent.bind("transitionend",endTrans);parent.bind("oTransitionEnd",endTrans)}}if(allowNavAnimations(firstLevelUl,firstItem)){parent.css("top",-height+"px")
}height+=(parent.height()+spacer);parent.changeDisplay("none")}needToAddMoreButton=true}else{if(index==threshold-1){if($.uaMatch(navigator.userAgent).browser!="msie"){spacer=parent.offset().top;lastHeight=parent.height()
}}}}})}if(needToAddMoreButton){btn=createLastNavButton(navContainer,"more",isSubNavigation);firstLevelUl.append(btn)}var fix=new Array();firstLevelUl.find("li").each(function(key,value){var li=$(this);
if(li.css("display")=="inline-block"){fix[key]=true;li.css("display","inline")}else{fix[key]=false}});firstLevelUl.find("li").each(function(key,value){if(fix[key]){var li=$(this);if(li.css("display")=="inline"){li.css("display","inline-block")
}}})}}function isSpecialBrowser(){if(($.browser.msie||!isBrowserSupportTransitions())&&!$.browser.mozilla){return true}else{return false}}_afterExpandCollapse=function(){if(afterExpCol){afterExpCol()}};
function showBackToHome(){if($(Parameters.NavigationAreaParams.BlockContainerSelector).length==0){return false}else{if($(Parameters.HomeLinkSelector).length>0){return false}else{var back=$("<a></a>");back.addClass("dmHome");
back.changeDisplay("block");back.attr("href",_.getHomeLink());back.html("<span class='icon'></span><span id='DM_HomeText' class='text'>"+Parameters.HomeLinkText+"</span>");$(Parameters.NavigationAreaParams.BlockContainerSelector).prepend(back);
initAjaxLinks(Parameters.HomeLinkSelector)}}}function createLastNavButton(navContainer,type,isSubNavigation){if(isSubNavigation==null){isSubNavigation=false}var navAnchor=$("#navAnchor");if(navAnchor.length==0){navAnchor=$("<a></a>");
navAnchor.attr("name","nav");navAnchor.attr("id","navAnchor");navAnchor.insertBefore(navContainer.parent())}var offsprings=navContainer.children("li:has(a):not(.dmHideFromNav)");var navItemsType="li";if(offsprings.length==0){offsprings=navContainer.children("a");
navItemsType="a"}var btn=$([]);if(navItemsType=="li"){if(btn.length==0){btn=$('<li class="p_list_item p_list_last"></li>')}var hrefClass=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).find("a").attr("className");
if(typeof hrefClass==="undefined"){hrefClass=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).find("a").attr("class")}var displayValue=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).css("display");
var height=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).height();if(type=="more"){btn.addClass("dmMore");btn.removeClass("dmLess");btn.attr("id","dmMore");btn.html('<a onclick="jQuery.DM.expandNavigation('+isSubNavigation+");_afterExpandCollapse();return false;\" href=\"#\" class='dmUDNavigationItem_dmMore dmMorea dmNavigationMoreAnchor'><div class='navIconBg'><div class='navIcon'></div></div><div id='dmMoreNavText' class='navText'>"+Parameters.NavigationAreaParams.MoreButtonText+"</div><div class='navArrowBg'><div class='navArrow'></div></div></a>")
}else{if(type=="less"){btn.addClass("dmLess");btn.removeClass("dmMore");btn.attr("id","dmLess");btn.html("<a id='dmLess' onclick=\"jQuery.DM.collapseNavigation("+isSubNavigation+");_afterExpandCollapse();return false;\" href=\"#\" class='dmUDNavigationItem_dmLess dmLessa dmNavigationLessAnchor'><div class='navIconBg'><div class='navIcon'></div></div><div id='dmLessNavText' class='navText'>"+Parameters.NavigationAreaParams.LessButtonText+"</div><div class='navArrowBg'><div class='navArrow'></div></div></a>")
}}}else{if(navItemsType=="a"){if(btn.length==0){btn=$('<a class="p_list_item p_list_last"></a>')}var hrefClass=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).attr("className");if(typeof hrefClass==="undefined"){hrefClass=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).attr("class")
}var displayValue=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).css("display");var height=offsprings.eq(Parameters.NavigationAreaParams.NavbarSize-1).height();if(type=="more"){btn.attr("id","dmMore");
btn.addClass("dmNavigationMoreAnchor");btn.addClass("dmMore");btn.removeClass("dmLess");btn.unbind("click").click(function(event){jQuery.DM.expandNavigation(isSubNavigation)});btn.text(Parameters.NavigationAreaParams.MoreButtonText)
}else{if(type=="less"){btn.attr("id","dmLess");btn.addClass("dmNavigationLessAnchor");btn.addClass("dmLess");btn.removeClass("dmMore");btn.unbind("click").click(function(event){jQuery.DM.collapseNavigation(isSubNavigation)
});btn.text(Parameters.NavigationAreaParams.LessButtonText)}}btn.css("cursor","pointer")}}if(allowNavAnimations(navContainer,offsprings.eq(0))){btn.css("position","relative")}btn.changeDisplay(displayValue);
if(type=="more"&&allowNavAnimations(navContainer,offsprings.eq(0))){btn.css("opacity","1")}if(type=="less"&&allowNavAnimations(navContainer,offsprings.eq(0))){btn.css("opacity","0")}return btn}function allowNavAnimations(navigationElement,navItemElement){if(isBrowserSupportTransitions()&&navItemElement.css("display").indexOf("inline")==-1&&navigationElement.css("display").indexOf("inline")==-1){return true
}else{return false}}function isBrowserSupportTransitions(){var browser={};var matched=$.uaMatch(navigator.userAgent);browser[matched.browser]=true;browser.version=matched.version;if(browser.chrome||browser.webkit||browser.safari){return true
}else{if(browser.mozilla){if(browser.version.startsWith("1.")||browser.version.startsWith("8")||browser.version.startsWith("9")){return false}else{return true}}else{if(browser.msie){return false}else{if(_userAgent==Enum.AgentType.WindowsMobile){return false
}else{if(browser.opera){return false}}}}}return false}function log(){if(arguments.length>0){var args=(arguments.length>1)?Array.prototype.join.call(arguments," "):arguments[0];try{console.log(args);return true
}catch(e){try{opera.postError(args);return true}catch(e){}}return false}}function callbackHistoryInitNoAjax(href){window.location.href=href}function callbackHistoryInit(href){if(href.startsWith("PhotoSwipe")){return
}if(_currentPage!=null&&href==_currentPage.pageID){return}if(_nextPage.pageReady){_nextPage=findInCache(href);if(_nextPage!=null){_nextPage=createPageFromCachedJson(_nextPage);if(_nextPage.pageContent!=null){if(!_nextPage.equals(_currentPage)){_nextPage.pageAnimation="backward"
}_nextPage.show()}else{}}else{_nextPage=findInCache(_LandingPageIdentifier);if(_nextPage!=null){_nextPage.pageAnimation="backward";_nextPage.show()}else{}}}}function isSidebarEmpty(){var sidebar=$(Parameters.SidebarParams.SidebarSelector);
var blockContainer=$(Parameters.NavigationAreaParams.BlockContainerSelector);if(sidebar.length==0){return true}if(sidebar.children().size()==2){if(sidebar.children().eq(0).hasClass(Parameters.SidebarParams.SidebarInitialClass)&&sidebar.children().eq(1).hasClass(Parameters.SidebarParams.SidebarClosingClass)){return true
}}if(blockContainer.length==0){return true}return false}function initHistory(){if(Parameters.AllowAjax){$.history.init(callbackHistoryInit);createHistoryEntryForCurrentPage()}else{$.history.init(callbackHistoryInitNoAjax)
}}$(document).ready(function(){try{retrieveJqueryVar();if((new RegExp("android","gi")).test(navigator.appVersion)){_userAgent=Enum.AgentType.Android}else{if((navigator.userAgent.match(/iPhone/i))||(navigator.userAgent.match(/iPod/i))||(navigator.userAgent.match(/iPad/i))){_userAgent=Enum.AgentType.Iphone
}else{if(navigator.userAgent.match(/BlackBerry/i)){_userAgent=Enum.AgentType.BlackBerry}else{if(navigator.userAgent.match(/Windows Phone/i)||(navigator.userAgent.match(/iEMobile/i))){_userAgent=Enum.AgentType.WindowsMobile
}}}}if(Parameters.CurrentThemeName.indexOf("NoiseBG")!=-1){_ThemeType=Enum.ThemeType.Matrix}if(_userAgent==Enum.AgentType.WindowsMobile||isIE7()){Parameters.AllowAjax=false}if(_userAgent==Enum.AgentType.Android){var style=$("<style>* {-webkit-tap-highlight-color: rgba(0, 0, 0, 0); }</style>");
$("head").append(style)}_.updateWidth();try{initFramework()}catch(e){log("DMAjax says: general error thrown from the initFramework method")}$("body, html").scrollTop(0);if(Parameters.AllowAjax){initAjaxLinks()
}if(Parameters.StartupCommand!=null){try{Parameters.StartupCommand()}catch(e){log("DMAjax says: problem with startup command")}}}catch(e){log("DMAjax says: general error thrown from the document ready method")
}})})(jQuery);function dm_gaq_push_url(a){if(_dm_gaq.systemGaqID){_gaq.push(["_trackPageview",a])}if(_dm_gaq.systemAggregatedGaqID&&(_dm_gaq.systemAggregatedGaqID!=_dm_gaq.systemGaqID)){_gaq.push(["b._trackPageview",a])
}if(_dm_gaq.externalGaqID){_gaq.push(["c._trackPageview",a])}if(_paq!=null){_paq.push(["trackPageView",a])}}function dm_gaq_push_event(a,c,b){if(_dm_gaq.systemGaqID){_gaq.push(["_trackEvent",a,_dm_gaq.siteAlias,c,b])
}if(_dm_gaq.systemAggregatedGaqID&&(_dm_gaq.systemAggregatedGaqID!=_dm_gaq.systemGaqID)){_gaq.push(["b._trackEvent",a,_dm_gaq.siteAlias,c,b])}if(_dm_gaq.externalGaqID){_gaq.push(["c._trackEvent",a,_dm_gaq.siteAlias,c,b])
}}String.prototype.startsWith=function(a){return(this.indexOf(a)===0)};String.prototype.endsWith=function(a){return(this.match(a+"$")==a)};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")
};replaceAll=function(c,a,b){return c.replace(new RegExp(a,"g"),b)};function replaceElements(a,b){jQuery(".hiddenSubMenu").each(function(c){jQuery(this).addClass("display_None_important")});jQuery("#"+a).addClass("display_None_important");
jQuery("#"+b).removeClass("display_None_important");jQuery("#"+b).removeClass("dmDisplay_None")}(function(a){a.fn.blink=function(d){if(d=="stop"){return this.data("blinkStop",true).stop(true,true).show()
}this.data("blinkStop",false);d=a.extend({},{fadeIn:100,fadeOut:300},d||{});function c(e){e=e||a(this);if(e.data("blinkStop")){return}e.fadeOut(d.fadeOut,b)}function b(e){e=e||a(this);if(e.data("blinkStop")){return
}e.fadeIn(d.fadeIn,c)}c(this);return this}})(jQuery);(function(a){_hideMe=function(e,c){if(e){var b=a(e);var d=b.closest("ul");b.closest("li").remove();a("#"+c).before(d);a("#"+c).closest("ul").changeDisplay("");
a("#"+c).remove()}};_launchHashed=function(g){if(g){var i=a(g);var c=i.closest("li");var f=c.find("ul:first");if(f.find("li").size()>0){var e=c.closest("ul");var h=c.attr("id");var d=a('<li class="p_list_item dmBackToMenuLi"></li>');
d.addClass("dmMore");d.attr("id","dmMore");var b=i.attr("btmTitle")||"Back to menu";d.html("<a href='#' onclick=\"var event = arguments[0] || window.event;_hideMe(this,'placeHolder_"+h+"');event.stopPropagation();_afterExpandCollapse();return false;\" class='dmUDNavigationItem_dmLess dmBackToMenuA'><div class='navIconBg'><div class='navIcon'></div></div><div class='navText'>"+b+"</div><div class='navArrowBg'><div class='navArrow'></div></div></a>");
f.prepend(d);f.after("<div class='hashedPlaceHolder' id='placeHolder_"+h+"'></div>");f.insertAfter(e);f.removeClass("dmDisplay_None");e.changeDisplay("none");_afterExpandCollapse()}}};a.fn.changeDisplay=function(d,c){if(d){d=d.replace("!important","");
a(this).css("display","");var b=c?"":" !important";a(this).attr("style",(a(this).attr("style")?a(this).attr("style")+";":"")+"display: "+d+b)}if(d==""){a(this).css("display",d)}};a.fn.dmCss=function(b,d){if(!d){return a(this).css(b)
}if(d==""){return a(this).css(b,"")}else{var c=d.indexOf("!important")!=-1;if(c){d=d.replace("!important","");a(this).css(b,"");a(this).each(function(){var e=a(this).attr("style");a(this).attr("style",(e?e+";":"")+b+": "+d+" !important")
});return a(this)}else{return a(this).css(b,d)}}};a.fn.naturalSize=function(){var b=this;if(b){var c=a(b);if(c.is("img")){if(c.prop("naturalWidth")==undefined){var d=a("<img/>").attr("src",c.attr("src"));
c.prop("naturalWidth",d[0].width);c.prop("naturalHeight",d[0].height)}return{width:c.prop("naturalWidth"),height:c.prop("naturalHeight")}}}return{}};a.fn.centerImageWithin=function(k,d){d=d||{};var g=a(this);
var p=a(k);if(g.is("img")&&p.length>0){g.attr("dm","true");var i=g.naturalSize();var b=i.height;var c=i.width;if(!b||!c||b*c==0){var q=g.attr("dm_crop_dim");var j=false;if(q){var n=q.split("_");if(n&&n.length==4){b=n[3];
c=n[2];j=true}}if(!j){b=g.attr("irh");c=g.attr("irw")}}if(!b||!c||b*c==0){return false}var m=(d.forceContainerHeight||k.height());var h=(d.forceContainerWidth||k.width());var l;var o=!d.stretch&&(c<=h)&&(b<=m);
g.css("height","");g.css("left","");g.css("width","");g.css("top","");g.css("max-width","none");if(o){l=Math.ceil(b)-m;g.css("top",""+(0-(l/2))+"px")}else{var s=(h/c)*b;var r=(m/b)*c;var f=(s>=m);var e=(d.stretch&&f)||(!d.stretch&&!f);
if(e){g.dmCss("width",h+"px !important");g.dmCss("max-width",h+"px !important");g.dmCss("min-width",h+"px !important");g.dmCss("height",Math.ceil(s)+"px !important");l=Math.ceil(s)-m;g.css("top",""+(0-(l/2))+"px")
}else{g.dmCss("height",m+"px !important");g.dmCss("width",Math.ceil(r)+"px !important");g.dmCss("max-width",Math.ceil(r)+"px !important");g.dmCss("min-width",Math.ceil(r)+"px !important");l=Math.ceil(r)-h;
if(d.stretch){g.css("left",""+(0-(l/2))+"px")}}}return true}}})(jQuery);var dmShareWasInit=false;var dmShareFirstRun=true;function dmInitShareIfNeeded(){if(!dmShareWasInit){$(window).unbind("resize.share").bind("resize.share",function(){$("body > .dmSharePopup").css("top",(jQuery(window).scrollTop()+10)+"px").css("width",(jQuery(window).width()-20)+"px").css("height",(jQuery(window).height()-20)+"px")
});$scrollingDiv=jQuery(".dmFloatingShare");height=window.innerHeight?window.innerHeight:jQuery(window).height();dmShareWasInit=true}}jQuery.fn.center=function(){this.css("position","absolute");this.css("top",((jQuery(window).height()-this.outerHeight())/2)+jQuery(window).scrollTop()+"px");
this.css("left",((jQuery(window).width()-this.outerWidth())/2)+jQuery(window).scrollLeft()+"px");return this};function dmShowSharePopup(){dmInitShareIfNeeded();var a=jQuery(".dmSharePopup");var b=a.first();
a.not(b).remove();if(jQuery("body > .dmSharePopup").size()==0){jQuery(".dmSharePopup").appendTo("body")}jQuery("#dmSharePopupMask").height(document.body.offsetHeight).width(jQuery(window).width()).show();
jQuery("body > .dmSharePopup").find("*").andSelf().each(function(){var c=$(this).attr("class");if(c){$(this).attr("class","");$(this).attr("class",c)}});jQuery("body > .dmSharePopup").show().css("top",(jQuery(window).scrollTop()+10)+"px").css("width",(jQuery(window).width()-20)+"px").css("height",(jQuery(window).height()-20)+"px");
if(window.event){window.event.stopPropagation()}return false}function dmHideSharePopup(a){jQuery("#dmSharePopupMask").hide();jQuery(".dmSharePopup").hide();if(a){a.cancelBubble=true;a.stopPropagation()
}return false}var hexcase=0;var b64pad="";function hex_sha1(c){var b=0;var d=rstr2hex(rstr_sha1(str2rstr_utf8(c)));for(var a=0;a<d.length;a++){b+=d.charCodeAt(a)}return b}function b64_sha1(a){return rstr2b64(rstr_sha1(str2rstr_utf8(a)))
}function any_sha1(a,b){return rstr2any(rstr_sha1(str2rstr_utf8(a)),b)}function hex_hmac_sha1(a,b){return rstr2hex(rstr_hmac_sha1(str2rstr_utf8(a),str2rstr_utf8(b)))}function b64_hmac_sha1(a,b){return rstr2b64(rstr_hmac_sha1(str2rstr_utf8(a),str2rstr_utf8(b)))
}function any_hmac_sha1(a,c,b){return rstr2any(rstr_hmac_sha1(str2rstr_utf8(a),str2rstr_utf8(c)),b)}function sha1_vm_test(){return hex_sha1("abc").toLowerCase()=="a9993e364706816aba3e25717850c26c9cd0d89d"
}function rstr_sha1(a){return binb2rstr(binb_sha1(rstr2binb(a),a.length*8))}function rstr_hmac_sha1(c,f){var e=rstr2binb(c);if(e.length>16){e=binb_sha1(e,c.length*8)}var a=Array(16),d=Array(16);for(var b=0;
b<16;b++){a[b]=e[b]^909522486;d[b]=e[b]^1549556828}var g=binb_sha1(a.concat(rstr2binb(f)),512+f.length*8);return binb2rstr(binb_sha1(d.concat(g),512+160))}function rstr2hex(c){try{hexcase}catch(g){hexcase=0
}var f=hexcase?"0123456789ABCDEF":"0123456789abcdef";var b="";var a;for(var d=0;d<c.length;d++){a=c.charCodeAt(d);b+=f.charAt((a>>>4)&15)+f.charAt(a&15)}return b}function rstr2b64(c){try{b64pad}catch(h){b64pad=""
}var g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";var b="";var a=c.length;for(var f=0;f<a;f+=3){var k=(c.charCodeAt(f)<<16)|(f+1<a?c.charCodeAt(f+1)<<8:0)|(f+2<a?c.charCodeAt(f+2):0);
for(var d=0;d<4;d++){if(f*8+d*6>c.length*8){b+=b64pad}else{b+=g.charAt((k>>>6*(3-d))&63)}}}return b}function rstr2any(k,c){var b=c.length;var j=Array();var h,a,l,e;var g=Array(Math.ceil(k.length/2));for(h=0;
h<g.length;h++){g[h]=(k.charCodeAt(h*2)<<8)|k.charCodeAt(h*2+1)}while(g.length>0){e=Array();l=0;for(h=0;h<g.length;h++){l=(l<<16)+g[h];a=Math.floor(l/b);l-=a*b;if(e.length>0||a>0){e[e.length]=a}}j[j.length]=l;
g=e}var d="";for(h=j.length-1;h>=0;h--){d+=c.charAt(j[h])}var f=Math.ceil(k.length*8/(Math.log(c.length)/Math.log(2)));for(h=d.length;h<f;h++){d=c[0]+d}return d}function str2rstr_utf8(c){var b="";var d=-1;
var a,e;while(++d<c.length){a=c.charCodeAt(d);e=d+1<c.length?c.charCodeAt(d+1):0;if(55296<=a&&a<=56319&&56320<=e&&e<=57343){a=65536+((a&1023)<<10)+(e&1023);d++}if(a<=127){b+=String.fromCharCode(a)}else{if(a<=2047){b+=String.fromCharCode(192|((a>>>6)&31),128|(a&63))
}else{if(a<=65535){b+=String.fromCharCode(224|((a>>>12)&15),128|((a>>>6)&63),128|(a&63))}else{if(a<=2097151){b+=String.fromCharCode(240|((a>>>18)&7),128|((a>>>12)&63),128|((a>>>6)&63),128|(a&63))}}}}}return b
}function str2rstr_utf16le(b){var a="";for(var c=0;c<b.length;c++){a+=String.fromCharCode(b.charCodeAt(c)&255,(b.charCodeAt(c)>>>8)&255)}return a}function str2rstr_utf16be(b){var a="";for(var c=0;c<b.length;
c++){a+=String.fromCharCode((b.charCodeAt(c)>>>8)&255,b.charCodeAt(c)&255)}return a}function rstr2binb(b){var a=Array(b.length>>2);for(var c=0;c<a.length;c++){a[c]=0}for(var c=0;c<b.length*8;c+=8){a[c>>5]|=(b.charCodeAt(c/8)&255)<<(24-c%32)
}return a}function binb2rstr(b){var a="";for(var c=0;c<b.length*32;c+=8){a+=String.fromCharCode((b[c>>5]>>>(24-c%32))&255)}return a}function binb_sha1(v,o){v[o>>5]|=128<<(24-o%32);v[((o+64>>9)<<4)+15]=o;
var y=Array(80);var u=1732584193;var s=-271733879;var r=-1732584194;var q=271733878;var p=-1009589776;for(var l=0;l<v.length;l+=16){var n=u;var m=s;var k=r;var h=q;var f=p;for(var g=0;g<80;g++){if(g<16){y[g]=v[l+g]
}else{y[g]=bit_rol(y[g-3]^y[g-8]^y[g-14]^y[g-16],1)}var z=safe_add(safe_add(bit_rol(u,5),sha1_ft(g,s,r,q)),safe_add(safe_add(p,y[g]),sha1_kt(g)));p=q;q=r;r=bit_rol(s,30);s=u;u=z}u=safe_add(u,n);s=safe_add(s,m);
r=safe_add(r,k);q=safe_add(q,h);p=safe_add(p,f)}return Array(u,s,r,q,p)}function sha1_ft(e,a,g,f){if(e<20){return(a&g)|((~a)&f)}if(e<40){return a^g^f}if(e<60){return(a&g)|(a&f)|(g&f)}return a^g^f}function sha1_kt(a){return(a<20)?1518500249:(a<40)?1859775393:(a<60)?-1894007588:-899497514
}function safe_add(a,d){var c=(a&65535)+(d&65535);var b=(a>>16)+(d>>16)+(c>>16);return(b<<16)|(c&65535)}function bit_rol(a,b){return(a<<b)|(a>>>(32-b))};